#@ TEMPLATE of `dev-spec completion powershell` - cli/completion.js fills each @@NAME@@ and drops these "#@" lines; never run it.
#@ Windows PowerShell 5.1 AND PowerShell 7: no ?: / ?? / && / ||, no -AsHashtable; a native argument completer (5.0+).
#@ A path or message with non-ASCII text is embedded as base64 (5.1 decodes a native command's output with the OEM code page).
# dev-spec completion for PowerShell (Windows PowerShell 5.1 and PowerShell 7) - generated by `dev-spec completion powershell`
# (dev-spec-driven @@VERSION@@) from the CLI's own tables. Save it, then load it from your profile:
#   node "@@CLI_TEXT@@" completion powershell > "$HOME\dev-spec-completion.ps1"
#   Add-Content $PROFILE '. "$HOME\dev-spec-completion.ps1"'
# It completes the commands, their flags, the values they take and the project's feature names (read from its .specs/ on Tab
# by `dev-spec __complete`). Without a dev-spec on PATH it also defines `dev-spec` (this CLI). In a plugin's versioned folder it
# follows a plugin update to the newest installed version; save it again after an update to complete new commands and flags.

$global:__DevSpecCliPath = @@CLI@@
$global:__DevSpecGone = @@GONE@@
$global:__DevSpecTables = @{
    Commands = @@COMMANDS@@
    Global = @@GLOBAL@@
    CmdGlobal = @@CMD_GLOBAL@@
    ValueFlags = @@VALUE_FLAGS@@
    # each command's flags (its own + --json --project --help)
    Flags = @@FLAGS@@
    # positional values: "<cmd>#<n>", "<cmd>#*" (every later one), "<cmd> <first word>#<n>"
    Args = @@ARGS@@
    # flag values: "<cmd> --<flag>", else "--<flag>"
    Values = @@VALUES@@
}

# Is version $a newer than $b? (dot-separated; each part's leading digits, else 0)
function global:__DevSpecNewer([string]$a, [string]$b) {
    $x = $a.Split('.'); $y = $b.Split('.')
    for ($i = 0; $i -lt [Math]::Max($x.Count, $y.Count); $i++) {
        $p = 0; $q = 0
        if ($i -lt $x.Count -and $x[$i] -match '^\d+') { $p = [double]$Matches[0] }
        if ($i -lt $y.Count -and $y[$i] -match '^\d+') { $q = [double]$Matches[0] }
        if ($p -ne $q) { return ($p -gt $q) }
    }
    return $false
}

# The CLI to run ($null: none) - in a plugin's versioned folder (...\dev-spec-driven\<version>\cli\dev-spec.js) the newest
# installed version, else this path while it exists.
function global:__DevSpecCli {
    $c = $global:__DevSpecCliPath
    $best = $null; $bestV = $null
    if ($c -match '^(.*)[\\/][^\\/]+[\\/]cli[\\/]dev-spec\.js$') {
        $root = $Matches[1]
        if ((Split-Path -Leaf $root) -eq 'dev-spec-driven' -and (Test-Path -LiteralPath $root -PathType Container)) {
            foreach ($d in @(Get-ChildItem -LiteralPath $root -Directory -ErrorAction SilentlyContinue)) {
                $f = Join-Path (Join-Path $d.FullName 'cli') 'dev-spec.js'
                if ((Test-Path -LiteralPath $f -PathType Leaf) -and ($null -eq $best -or (__DevSpecNewer $d.Name $bestV))) { $best = $f; $bestV = $d.Name }
            }
        }
    }
    if ($null -eq $best -and (Test-Path -LiteralPath $c -PathType Leaf)) { $best = $c }
    return $best
}

# A dev-spec on PATH (a global install), or $null.
function global:__DevSpecOnPath {
    $p = @(Get-Command dev-spec -CommandType Application -ErrorAction SilentlyContinue)
    if ($p.Count) { return $p[0].Source }
    return $null
}

# The project's feature names ($What: features | archived) - of the --project the line names, if any.
function global:__DevSpecNames([string]$What, [string]$Project) {
    $a = @('__complete', $What)
    if ($Project) { $a += @('--project', $Project) }
    $c = __DevSpecCli
    try {
        if ($c) { & node $c @a 2>$null }
        else { $p = __DevSpecOnPath; if ($p) { & $p @a 2>$null } }
    } catch { }
}

if (-not (Get-Command dev-spec -ErrorAction SilentlyContinue)) {
    # `dev-spec <command> ...` runs the CLI (piped input too): the one above, else a dev-spec on PATH. A list PowerShell parsed
    # from `--tracks tdd,saas` goes on as the one word "tdd,saas" (splatted as is it would become two words); every other argument
    # stays as it is in $args, so `--timebox 3d` is still "3d" (a copy would pass the number 3).
    function global:dev-spec {
        for ($i = 0; $i -lt $args.Count; $i++) { if ($args[$i] -is [array]) { $args[$i] = $args[$i] -join ',' } }
        $c = __DevSpecCli
        if ($c) {
            if ($MyInvocation.ExpectingInput) { $input | & node $c @args } else { & node $c @args }
            return
        }
        $p = __DevSpecOnPath
        if ($p) {
            if ($MyInvocation.ExpectingInput) { $input | & $p @args } else { & $p @args }
            return
        }
        [Console]::Error.WriteLine('dev-spec: ' + $global:__DevSpecGone)
        $global:LASTEXITCODE = 127
    }
}

Register-ArgumentCompleter -Native -CommandName 'dev-spec' -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)
    $tables = $global:__DevSpecTables  # (never $T: PowerShell names are case-blind, so $t below would replace it)
    # the words before the one being completed (the elements that end before the cursor)
    $words = New-Object System.Collections.Generic.List[string]
    $els = $commandAst.CommandElements
    for ($i = 1; $i -lt $els.Count; $i++) {
        $e = $els[$i]
        if ($e.Extent.EndOffset -ge $cursorPosition) { break }
        if ($e -is [System.Management.Automation.Language.StringConstantExpressionAst]) { $words.Add([string]$e.Value) } else { $words.Add($e.Extent.Text) }
    }
    $cur = [string]$wordToComplete
    $cmd = ''; $sub = ''; $n = 0; $expect = ''; $dd = $false; $proj = ''; $vflag = ''; $pre = ''
    foreach ($w in $words) {
        if ($expect) { if ($expect -eq '--project') { $proj = $w }; $expect = ''; continue }
        if (-not $dd) {
            if ($w -eq '--') { $dd = $true; continue }
            if ($w.StartsWith('--project=')) { $proj = $w.Substring(10); continue }
            if (($w.StartsWith('--') -and $w.Contains('=')) -or $w -ceq '-h' -or $w -ceq '-V') { continue }
            if ($w.StartsWith('--')) { if ($tables.ValueFlags -contains $w) { $expect = $w }; continue }
        }
        if (-not $cmd) { $cmd = $w } else { $n++; if ($n -eq 1) { $sub = $w } }
    }
    if (-not $dd -and $cur.StartsWith('--') -and $cur.Contains('=')) {
        $k = $cur.IndexOf('='); $vflag = $cur.Substring(0, $k); $pre = $cur.Substring(0, $k + 1); $cur = $cur.Substring($k + 1)
    } elseif ($expect) { $vflag = $expect }
    $spec = $null; $kind = 'ParameterValue'
    if ($vflag) {
        # a list value (--tracks tdd,saas ; depend --add a,b): its last item
        if ($cur.Contains(',')) { $k = $cur.LastIndexOf(','); $pre += $cur.Substring(0, $k + 1); $cur = $cur.Substring($k + 1) }
        if ($tables.Values.ContainsKey("$cmd $vflag")) { $spec = $tables.Values["$cmd $vflag"] } elseif ($tables.Values.ContainsKey($vflag)) { $spec = $tables.Values[$vflag] }
    } elseif (-not $dd -and $cur.StartsWith('-')) {
        $kind = 'ParameterName'
        if (-not $cmd) { $spec = $tables.Global -join ' ' } elseif ($tables.Flags.ContainsKey($cmd)) { $spec = $tables.Flags[$cmd] } else { $spec = $tables.CmdGlobal -join ' ' }
    } elseif (-not $cmd) {
        $spec = '@command'
    } else {
        $n++
        $keys = @()
        if ($n -ge 2) { $keys += @("$cmd $sub#$n", "$cmd $sub#*") }
        $keys += @("$cmd#$n", "$cmd#*")
        foreach ($k in $keys) { if ($tables.Args.ContainsKey($k)) { $spec = $tables.Args[$k]; break } }
    }
    if ($null -eq $spec) { return }
    $cands = New-Object System.Collections.Generic.List[string]
    foreach ($t in ([string]$spec).Split(' ', [StringSplitOptions]::RemoveEmptyEntries)) {
        if ($t -ceq '@feature' -or $t -ceq '@archived') {
            $what = 'features'; if ($t -ceq '@archived') { $what = 'archived' }
            foreach ($x in @(__DevSpecNames $what $proj)) { if ($x) { $cands.Add(([string]$x).Trim()) } }
        } elseif ($t -ceq '@command') { foreach ($x in $tables.Commands) { $cands.Add($x) } }
        elseif ($t -ceq '@file' -or $t -ceq '@dir') { }
        else { $cands.Add($t) }
    }
    foreach ($c in $cands) {
        if ($c.StartsWith($cur, [StringComparison]::OrdinalIgnoreCase)) {
            [System.Management.Automation.CompletionResult]::new($pre + $c, $c, $kind, $c)
        }
    }
}
