#@ TEMPLATE of `dev-spec completion fish` — cli/completion.js fills each @@NAME@@ and drops these "#@" lines; never source it.
#@ fish 3.x / 4.x: the same algorithm and tables as the bash script; the candidates are printed one per line (fish filters them).
# dev-spec completion for fish — generated by `dev-spec completion fish` (dev-spec-driven @@VERSION@@) from the CLI's own tables.
# Save it where fish loads it at startup (conf.d — it also defines the dev-spec command):
#   node "@@CLI_TEXT@@" completion fish > ~/.config/fish/conf.d/dev-spec.fish
# It completes the commands, their flags, the values they take and the project's feature names (read from its .specs/ on Tab
# by `dev-spec __complete`). Without a dev-spec on PATH it also defines `dev-spec` (this CLI). In a plugin's versioned folder it
# follows a plugin update to the newest installed version; save it again after an update to complete new commands and flags.

set -g __dev_spec_cli_path @@CLI@@
set -g __dev_spec_commands @@COMMANDS@@
set -g __dev_spec_global @@GLOBAL@@
set -g __dev_spec_cmd_global @@CMD_GLOBAL@@

# Is version $argv[1] newer than $argv[2]? (dot-separated; each part's leading digits, else 0)
function __dev_spec_newer
    set -l a (string split . -- $argv[1])
    set -l b (string split . -- $argv[2])
    for i in 1 2 3 4 5 6 7 8
        set -l x 0
        set -l y 0
        if test (count $a) -ge $i
            set -l d (string match -r -- '^[0-9]+' $a[$i])
            test -n "$d"; and set x $d
        end
        if test (count $b) -ge $i
            set -l d (string match -r -- '^[0-9]+' $b[$i])
            test -n "$d"; and set y $d
        end
        test $x -gt $y; and return 0
        test $x -lt $y; and return 1
    end
    return 1
end

# The CLI to run (printed; nothing: none) — in a plugin's versioned folder (…/dev-spec-driven/<version>/cli/dev-spec.js) the
# newest installed version, else this path while it exists.
function __dev_spec_cli
    set -l c $__dev_spec_cli_path
    set -l best ''
    set -l bestv ''
    if string match -q -- '*/dev-spec-driven/*/cli/dev-spec.js' $c
        set -l root (string replace -r -- '/[^/]+/cli/dev-spec\.js$' '' $c)
        for f in $root/*/cli/dev-spec.js
            test -f $f; or continue
            set -l v (string replace -r -- '/cli/dev-spec\.js$' '' $f | string replace -r -- '^.*/' '')
            if test -z "$best"; or __dev_spec_newer $v $bestv
                set best $f
                set bestv $v
            end
        end
    end
    if test -z "$best"; and test -f $c
        set best $c
    end
    test -n "$best"; and string join '' -- $best
end

# Run the CLI with $argv: the one above, else a dev-spec on PATH.
function __dev_spec_run
    set -l c (__dev_spec_cli)
    if test -n "$c"
        node $c $argv
        return $status
    end
    if type -q -f dev-spec
        command dev-spec $argv
        return $status
    end
    echo 'dev-spec: '@@GONE@@ >&2
    return 127
end

# The project's feature names ($argv[1]: features | archived) — of the --project the line names ($argv[2]), if any.
function __dev_spec_names
    set -l p (string replace -r -- '^~(?=/|$)' $HOME "$argv[2]")
    if test -n "$p"
        __dev_spec_run __complete $argv[1] --project $p 2>/dev/null
    else
        __dev_spec_run __complete $argv[1] 2>/dev/null
    end
end

# Each command's flags (its own + --json --project --help).
@@FLAGS@@

# Positional values: "<cmd>#<n>", "<cmd>#*" (every later one), "<cmd> <first word>#<n>".
@@ARGS@@

# Flag values: "<cmd> --<flag>", else "--<flag>".
@@VALUES@@

# The flags that take a value (the next word is that value, never a positional).
function __dev_spec_is_vflag
    contains -- $argv[1] @@VALUE_FLAGS@@
end

# Print one spec's candidates: $argv[1] the spec, [2] the word so far, [3] a prefix they keep ("--lang=", "tdd,"), [4] --project.
function __dev_spec_offer
    for t in (string split ' ' -- $argv[1])
        if test "x$t" = x@feature; or test "x$t" = x@archived
            set -l what features
            test "x$t" = x@archived; and set what archived
            for x in (__dev_spec_names $what $argv[4])
                string join '' -- $argv[3]$x
            end
        else if test "x$t" = x@command
            string split ' ' -- $__dev_spec_commands
        else if test "x$t" = x@file
            __fish_complete_path $argv[2]
        else if test "x$t" = x@dir
            __fish_complete_directories $argv[2]
        else if test -n "$t"
            string join '' -- $argv[3]$t
        end
    end
end

function __dev_spec_complete
    set -l tokens (commandline -opc)
    set -l cur (commandline -ct)
    set -e tokens[1]
    set -l cmd ''
    set -l sub ''
    set -l n 0
    set -l expect ''
    set -l dd ''
    set -l proj ''
    set -l vflag ''
    set -l pre ''
    set -l r ''
    for w in $tokens
        if test -n "$expect"
            test "x$expect" = x--project; and set proj $w
            set expect ''
            continue
        end
        if test -z "$dd"
            if test "x$w" = x--
                set dd 1
                continue
            else if string match -q -- '--project=*' $w
                set proj (string replace -- '--project=' '' $w)
                continue
            else if string match -q -- '--*=*' $w; or contains -- $w -h -V
                continue
            else if string match -q -- '--*' $w
                __dev_spec_is_vflag $w; and set expect $w
                continue
            end
        end
        if test -z "$cmd"
            set cmd $w
        else
            set n (math $n + 1)
            test $n -eq 1; and set sub $w
        end
    end
    if test -z "$dd"; and string match -q -- '--*=*' $cur
        set vflag (string replace -r -- '=.*$' '' $cur)
        set pre $vflag=
        set cur (string replace -r -- '^[^=]*=' '' $cur)
    else if test -n "$expect"
        set vflag $expect
    end
    if test -n "$vflag"
        # a list value (--tracks tdd,saas · depend --add a,b): its last item
        if string match -q -- '*,*' $cur
            set pre $pre(string replace -r -- '[^,]*$' '' $cur)
            set cur (string replace -r -- '^.*,' '' $cur)
        end
        if set r (__dev_spec_val "$cmd $vflag"); or set r (__dev_spec_val $vflag)
            __dev_spec_offer "$r" "$cur" "$pre" "$proj"
        end
        return 0
    end
    if test -z "$dd"; and string match -q -- '-*' $cur
        if test -z "$cmd"
            set r $__dev_spec_global
        else if not set r (__dev_spec_flags $cmd)
            set r $__dev_spec_cmd_global
        end
        string split ' ' -- $r
        return 0
    end
    if test -z "$cmd"
        string split ' ' -- $__dev_spec_commands
        return 0
    end
    set n (math $n + 1)
    set -l found 1
    if test $n -ge 2
        set r (__dev_spec_arg "$cmd $sub#$n"); or set r (__dev_spec_arg "$cmd $sub#*"); or set found 0
    else
        set found 0
    end
    if test $found -eq 0
        set r (__dev_spec_arg "$cmd#$n"); or set r (__dev_spec_arg "$cmd#*"); or return 0
    end
    __dev_spec_offer "$r" "$cur" '' "$proj"
end

if not type -q dev-spec
    function dev-spec --description 'dev-spec-driven CLI'
        __dev_spec_run $argv
    end
end
complete -c dev-spec -f -a '(__dev_spec_complete)'
