#@ TEMPLATE of `dev-spec completion zsh` — cli/completion.js fills each @@NAME@@ and drops these "#@" lines; never source it.
#@ Native zsh (compsys): the same algorithm and tables as the bash script; compset moves a "--flag=" / "a," prefix aside.
# dev-spec completion for zsh — generated by `dev-spec completion zsh` (dev-spec-driven @@VERSION@@) from the CLI's own tables.
# Save it, then load it from ~/.zshrc AFTER compinit:
#   node "@@CLI_TEXT@@" completion zsh > ~/.dev-spec-completion.zsh
#   echo '. ~/.dev-spec-completion.zsh' >> ~/.zshrc
# It completes the commands, their flags, the values they take and the project's feature names (read from its .specs/ on Tab
# by `dev-spec __complete`). Without a dev-spec on PATH it also defines `dev-spec` (this CLI). In a plugin's versioned folder it
# follows a plugin update to the newest installed version; save it again after an update to complete new commands and flags.

typeset -g __dev_spec_cli_path=@@CLI@@
typeset -g __dev_spec_commands=@@COMMANDS@@
typeset -g __dev_spec_global=@@GLOBAL@@
typeset -g __dev_spec_cmd_global=@@CMD_GLOBAL@@
typeset -g __dev_spec_r=

# The CLI to run, in __dev_spec_r (empty: none) — in a plugin's versioned folder (…/dev-spec-driven/<version>/cli/dev-spec.js)
# the newest installed version, else this path while it exists.
__dev_spec_cli() {
    emulate -L zsh
    local c=$__dev_spec_cli_path f v best= bestv=
    if [[ $c == */dev-spec-driven/*/cli/dev-spec.js ]]; then
        for f in "${c%/*/cli/dev-spec.js}"/*/cli/dev-spec.js(N); do
            [[ -f $f ]] || continue
            v=${f%/cli/dev-spec.js}; v=${v:t}
            if [[ -z $best ]] || __dev_spec_newer $v $bestv; then best=$f; bestv=$v; fi
        done
    fi
    [[ -z $best && -f $c ]] && best=$c
    __dev_spec_r=$best
}

# Is version $1 newer than $2? (dot-separated; each part's leading digits, else 0)
__dev_spec_newer() {
    emulate -L zsh
    local -a a b
    local i x y
    a=("${(@s:.:)1}"); b=("${(@s:.:)2}")
    for (( i = 1; i <= ${#a} || i <= ${#b}; i++ )); do
        x=${a[i]%%[^0-9]*}; y=${b[i]%%[^0-9]*}
        (( ${x:-0} > ${y:-0} )) && return 0
        (( ${x:-0} < ${y:-0} )) && return 1
    done
    return 1
}

# Run the CLI with "$@": the one above, else a dev-spec on PATH.
__dev_spec_run() {
    __dev_spec_cli
    if [[ -n $__dev_spec_r ]]; then node "$__dev_spec_r" "$@"
    elif (( $+commands[dev-spec] )); then command dev-spec "$@"
    else print -ru2 -- "dev-spec: "@@GONE@@; return 127
    fi
}

# The project's feature names ($1: features | archived) — of the --project the line names ($2), if any.
__dev_spec_names() {
    emulate -L zsh
    local p=${(Q)2}
    [[ $p == "~" || $p == "~/"* ]] && p=$HOME${p#\~}
    if [[ -n $p ]]; then __dev_spec_run __complete $1 --project $p 2>/dev/null
    else __dev_spec_run __complete $1 2>/dev/null
    fi
}

# Each command's flags (its own + --json --project --help).
@@FLAGS@@

# Positional values: "<cmd>#<n>", "<cmd>#*" (every later one), "<cmd> <first word>#<n>".
@@ARGS@@

# Flag values: "<cmd> --<flag>", else "--<flag>".
@@VALUES@@

# The flags that take a value (the next word is that value, never a positional).
__dev_spec_is_vflag() {
    case $1 in @@VALUE_FLAGS@@) return 0 ;; esac
    return 1
}

# Offer one spec's candidates: $1 the spec, $2 the line's --project.
__dev_spec_offer() {
    local t
    local -a w
    for t in ${=1}; do
        case $t in
            @feature) w+=(${(f)"$(__dev_spec_names features $2)"}) ;;
            @archived) w+=(${(f)"$(__dev_spec_names archived $2)"}) ;;
            @command) w+=(${=__dev_spec_commands}) ;;
            @file) _files ;;
            @dir) _files -/ ;;
            *) w+=($t) ;;
        esac
    done
    (( ${#w} )) && compadd -- "${w[@]}"
}

_dev_spec() {
    local cur=${words[CURRENT]} i w cmd= sub= n=0 expect= dd= proj= vflag=
    for (( i = 2; i < CURRENT; i++ )); do
        w=${words[i]}
        if [[ -n $expect ]]; then [[ $expect == --project ]] && proj=$w; expect=; continue; fi
        if [[ -z $dd ]]; then
            case $w in
                --) dd=1; continue ;;
                --project=*) proj=${w#*=}; continue ;;
                --*=*|-h|-V) continue ;;
                --*) __dev_spec_is_vflag $w && expect=$w; continue ;;
            esac
        fi
        if [[ -z $cmd ]]; then cmd=$w; else n=$(( n + 1 )); (( n == 1 )) && sub=$w; fi
    done
    if [[ -z $dd && $cur == --*=* ]]; then vflag=${cur%%=*}; compset -P '*='; cur=${cur#*=}
    elif [[ -n $expect ]]; then vflag=$expect
    fi
    if [[ -n $vflag ]]; then
        # a list value (--tracks tdd,saas · depend --add a,b): its last item
        [[ $cur == *,* ]] && compset -P '*,'
        if __dev_spec_val "${cmd} ${vflag}" || __dev_spec_val $vflag; then __dev_spec_offer "$__dev_spec_r" "$proj"; fi
        return 0
    fi
    if [[ -z $dd && $cur == -* ]]; then
        if [[ -z $cmd ]]; then __dev_spec_r=$__dev_spec_global
        elif ! __dev_spec_flags $cmd; then __dev_spec_r=$__dev_spec_cmd_global
        fi
        compadd -- ${=__dev_spec_r}
        return 0
    fi
    if [[ -z $cmd ]]; then compadd -- ${=__dev_spec_commands}; return 0; fi
    n=$(( n + 1 ))
    if { (( n >= 2 )) && { __dev_spec_arg "${cmd} ${sub}#${n}" || __dev_spec_arg "${cmd} ${sub}#*"; }; } ||
        __dev_spec_arg "${cmd}#${n}" || __dev_spec_arg "${cmd}#*"; then
        __dev_spec_offer "$__dev_spec_r" "$proj"
    fi
    return 0
}

if ! (( $+commands[dev-spec] || $+functions[dev-spec] || $+aliases[dev-spec] )); then
    dev-spec() { __dev_spec_run "$@"; }
fi
(( $+functions[compdef] )) && compdef _dev_spec dev-spec
