#@ TEMPLATE of `dev-spec completion bash` — cli/completion.js fills each @@NAME@@ and drops these "#@" lines; never source it.
#@ Plain bash 3.2+ (macOS ships 3.2: no associative arrays, no ${v,,}); compopt (bash 4) only where it exists.
#@ The tables are functions (`case`) that set __dev_spec_r and return 1 for a key they don't hold.
# dev-spec completion for bash — generated by `dev-spec completion bash` (dev-spec-driven @@VERSION@@) from the CLI's own tables.
# Save it, then load it from ~/.bashrc:
#   node "@@CLI_TEXT@@" completion bash > ~/.dev-spec-completion.bash
#   echo '. ~/.dev-spec-completion.bash' >> ~/.bashrc
# It completes the commands, their flags, the values they take and the project's feature names (read from its .specs/ on Tab
# by `dev-spec __complete`). Without a dev-spec on PATH it also defines `dev-spec` (this CLI). In a plugin's versioned folder it
# follows a plugin update to the newest installed version; save it again after an update to complete new commands and flags.
# shellcheck disable=SC2207,SC2088 # COMPREPLY=($(compgen …)): bash 3.2 has no mapfile · "~" is matched, not expanded

__dev_spec_cli_path=@@CLI@@
__dev_spec_commands=@@COMMANDS@@
__dev_spec_global=@@GLOBAL@@
__dev_spec_cmd_global=@@CMD_GLOBAL@@

# The CLI to run, in __dev_spec_r (empty: none) — in a plugin's versioned folder (…/dev-spec-driven/<version>/cli/dev-spec.js)
# the newest installed version, else this path while it exists.
__dev_spec_cli() {
    local c=$__dev_spec_cli_path f v best='' bestv=''
    case $c in
        */dev-spec-driven/*/cli/dev-spec.js)
            for f in "${c%/*/cli/dev-spec.js}"/*/cli/dev-spec.js; do
                [ -f "$f" ] || continue
                v=${f%/cli/dev-spec.js}; v=${v##*/}
                if [ -z "$best" ] || __dev_spec_newer "$v" "$bestv"; then best=$f; bestv=$v; fi
            done ;;
    esac
    if [ -z "$best" ] && [ -f "$c" ]; then best=$c; fi
    __dev_spec_r=$best
}

# Is version $1 newer than $2? (dot-separated; each part's leading digits, else 0)
__dev_spec_newer() {
    local a=$1. b=$2. x y
    while [ -n "$a$b" ]; do
        x=${a%%.*}; a=${a#*.}; y=${b%%.*}; b=${b#*.}
        x=${x%%[!0-9]*}; y=${y%%[!0-9]*}
        [ "${x:-0}" -gt "${y:-0}" ] && return 0
        [ "${x:-0}" -lt "${y:-0}" ] && return 1
    done
    return 1
}

# Run the CLI with "$@": the one above, else a dev-spec on PATH.
__dev_spec_run() {
    __dev_spec_cli
    if [ -n "$__dev_spec_r" ]; then node "$__dev_spec_r" "$@"
    elif type -P dev-spec >/dev/null 2>&1; then command dev-spec "$@"
    else printf 'dev-spec: %s\n' @@GONE@@ >&2; return 127
    fi
}

# The project's feature names ($1: features | archived) — of the --project the line names ($2), if any.
__dev_spec_names() {
    local p=$2
    case $p in \"*\") p=${p#\"}; p=${p%\"} ;; \'*\') p=${p#\'}; p=${p%\'} ;; esac
    case $p in "~") p=$HOME ;; "~/"*) p=$HOME/${p#"~/"} ;; esac
    if [ -n "$p" ]; then __dev_spec_run __complete "$1" --project "$p" 2>/dev/null
    else __dev_spec_run __complete "$1" 2>/dev/null
    fi
}

# Each command's flags (its own + --json --project --help).
@@FLAGS@@

# Positional values: "<cmd>#<n>", "<cmd>#*" (every later one), "<cmd> <first word>#<n>".
@@ARGS@@

# Flag values: "<cmd> --<flag>", else "--<flag>".
@@VALUES@@

# The flags that take a value (the next word is that value, never a positional).
__dev_spec_is_vflag() {
    case $1 in @@VALUE_FLAGS@@) return 0 ;; esac
    return 1
}

# Add one spec's candidates to COMPREPLY: $1 the spec, $2 the word so far, $3 a prefix the candidates keep ("--lang=", "=",
# "tdd,"), $4 the line's --project.
__dev_spec_offer() {
    local t w='' IFS=$' \t\n'
    for t in $1; do
        case $t in
            @feature) w="$w $(__dev_spec_names features "$4")" ;;
            @archived) w="$w $(__dev_spec_names archived "$4")" ;;
            @command) w="$w $__dev_spec_commands" ;;
            @file|@dir)
                compopt -o filenames 2>/dev/null
                IFS=$'\n'
                if [ "$t" = @dir ]; then COMPREPLY+=($(compgen -P "$3" -d -- "$2")); else COMPREPLY+=($(compgen -P "$3" -f -- "$2")); fi
                IFS=$' \t\n' ;;
            *) w="$w $t" ;;
        esac
    done
    if [ -n "$w" ]; then COMPREPLY+=($(compgen -P "$3" -W "$w" -- "$2")); fi
}

__dev_spec_complete() {
    COMPREPLY=()
    local cur=${COMP_WORDS[COMP_CWORD]} end=$COMP_CWORD i w cmd='' sub='' n=0 expect='' dd='' proj='' vflag='' pre=''
    # "--flag=value": bash's word breaks make it "--flag" "=" "value" (one word when "=" is no break)
    if [ "$cur" = "=" ] && [ "$COMP_CWORD" -ge 2 ]; then
        vflag=${COMP_WORDS[COMP_CWORD-1]}; pre="="; cur=; end=$((COMP_CWORD - 1))
    elif [ "$COMP_CWORD" -ge 3 ] && [ "${COMP_WORDS[COMP_CWORD-1]}" = "=" ]; then
        vflag=${COMP_WORDS[COMP_CWORD-2]}; end=$((COMP_CWORD - 2))
    fi
    for ((i = 1; i < end; i++)); do
        w=${COMP_WORDS[i]}
        if [ -z "$dd" ] && [ "$w" = "=" ]; then [ -z "$expect" ] && expect=-; continue; fi
        if [ -n "$expect" ]; then [ "$expect" = --project ] && proj=$w; expect=; continue; fi
        if [ -z "$dd" ]; then
            case $w in
                --) dd=1; continue ;;
                --project=*) proj=${w#*=}; continue ;;
                --*=*|-h|-V) continue ;;
                --*) __dev_spec_is_vflag "$w" && expect=$w; continue ;;
            esac
        fi
        if [ -z "$cmd" ]; then cmd=$w; else n=$((n + 1)); [ "$n" -eq 1 ] && sub=$w; fi
    done
    if [ -z "$vflag" ] && [ -z "$dd" ]; then
        case $cur in --*=*) vflag=${cur%%=*}; pre=${cur%%=*}=; cur=${cur#*=} ;; esac
    fi
    if [ -z "$vflag" ] && [ -n "$expect" ] && [ "$expect" != - ]; then vflag=$expect; fi
    if [ -n "$vflag" ]; then
        case $vflag in --*) ;; *) return 0 ;; esac
        # a list value (--tracks tdd,saas · depend --add a,b): its last item
        case $cur in *,*) pre=$pre${cur%,*},; cur=${cur##*,} ;; esac
        if __dev_spec_val "${cmd} ${vflag}" || __dev_spec_val "$vflag"; then __dev_spec_offer "$__dev_spec_r" "$cur" "$pre" "$proj"; fi
        return 0
    fi
    if [ -z "$dd" ]; then
        case $cur in
            -*)
                if [ -z "$cmd" ]; then __dev_spec_r=$__dev_spec_global
                elif ! __dev_spec_flags "$cmd"; then __dev_spec_r=$__dev_spec_cmd_global
                fi
                COMPREPLY=($(compgen -W "$__dev_spec_r" -- "$cur"))
                return 0 ;;
        esac
    fi
    if [ -z "$cmd" ]; then COMPREPLY=($(compgen -W "$__dev_spec_commands" -- "$cur")); return 0; fi
    n=$((n + 1))
    if { [ "$n" -ge 2 ] && { __dev_spec_arg "${cmd} ${sub}#${n}" || __dev_spec_arg "${cmd} ${sub}#*"; }; } ||
        __dev_spec_arg "${cmd}#${n}" || __dev_spec_arg "${cmd}#*"; then
        __dev_spec_offer "$__dev_spec_r" "$cur" "" "$proj"
    fi
    return 0
}

if ! type dev-spec >/dev/null 2>&1; then
    dev-spec() { __dev_spec_run "$@"; }
fi
complete -F __dev_spec_complete dev-spec
