#!/usr/bin/env node
"use strict";

/**
 * dev-spec-driven — local hook handler (zero-dependency).
 *
 * Wired from hooks/hooks.json for two events:
 *   - PostToolUse (Write|Edit): when a `.specs/.../requirements.md` is saved, lint EARS;
 *     when a `.specs/.../tasks.md` is saved, run a traceability check; when a `.specs/.../design.md`
 *     is saved, run its mandatory checks for the active tracks. Any spec edit also refreshes ROADMAP.md
 *     and, when it exists and is generated, the living catalog .specs/SPECS.md. Surfaces gaps in the
 *     moment, with zero CI and zero cost.
 *   - SessionStart: print a one-line status of the project's features (at most SESSION_MAX_FEATURES — the most
 *     relevant — then one "+N more" line), plus one line per finished
 *     active feature whose implementing files drifted since finish (bounded; see DRIFT_MAX_FILES), and one
 *     line when .specs/ comes from an older dev-spec (roadmap.json meta.specVersion) — run /spec-upgrade — and one
 *     line when features' open tasks plan the same files (cross-feature overlap; text reads only).
 *
 * It NEVER blocks: any error or irrelevant event exits 0 silently. Output is emitted as
 * `hookSpecificOutput.additionalContext` so Claude sees it as context, not as a user message.
 */

const fs = require("fs");
const path = require("path");

let spec;
try {
  spec = require(path.join(__dirname, "..", "mcp", "lib", "spec.js"));
} catch {
  process.exit(0); // engine not found — stay silent
}

let emitted = false;
let ran = false;
const DRIFT_MAX_FILES = 200; // SessionStart hashes at most this many recorded _Implements:_ files, else skips the drift check
const SESSION_MAX_FEATURES = 20; // SessionStart lists at most this many features (the most relevant), then "+N more — /spec-status"
// Emits exactly one JSON object and exits only after the write is flushed (Windows pipes truncate
// otherwise). Callers `return emit(...)` — nothing may call process.exit() after it.
function emit(eventName, text) {
  if (emitted) return;
  emitted = true;
  if (!text) process.exit(0);
  process.stdout.write(
    JSON.stringify({ hookSpecificOutput: { hookEventName: eventName, additionalContext: text } }),
    () => process.exit(0)
  );
}

// The hooks run in EVERY project. Only touch a .specs/ that dev-spec owns (another tool may use the name).
function isDevSpecProject(pdir) {
  const root = path.join(pdir, ".specs");
  if (fs.existsSync(path.join(root, "roadmap.json")) || fs.existsSync(path.join(root, "steering"))) return true;
  try {
    const rm = fs.readFileSync(path.join(root, "ROADMAP.md"), "utf8"); // generated by any dev-spec version
    if (/AUTO-GE(?:NERATED|RADO|NERADO) (?:by|por) dev-spec/.test(rm.slice(0, 4000))) return true;
  } catch { /* no roadmap */ }
  try {
    // .state.json (v1.9+) or classification.md (every spec_create) marks a dev-spec feature folder.
    return fs.readdirSync(root, { withFileTypes: true }).some((d) => d.isDirectory() &&
      (fs.existsSync(path.join(root, d.name, ".state.json")) || fs.existsSync(path.join(root, d.name, "classification.md"))));
  } catch {
    return false;
  }
}

function findProjectDir(filePath) {
  // Walk up from the file until we find the parent of a `.specs` directory.
  let dir = path.dirname(filePath);
  for (let i = 0; i < 12 && dir; i++) {
    if (path.basename(dir) === ".specs") return path.dirname(dir);
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return process.env.CLAUDE_PROJECT_DIR || process.env.SPEC_PROJECT_DIR || process.cwd();
}

function main(raw) {
  if (ran) return; // stdin 'end' and the safety-net timer must not both run the hook
  ran = true;
  // One hook event = one engine call: every spec file is read once across the steps below (roadmap, catalog, the
  // check), however many of them ask — the engine's own writes (ROADMAP.md, SPECS.md) keep that cache true.
  return spec.withReadCache(() => handle(raw));
}

function handle(raw) {
  let payload = {};
  try {
    payload = JSON.parse(raw || "{}");
  } catch {
    process.exit(0);
  }
  if (!payload || typeof payload !== "object") process.exit(0);
  const event = payload.hook_event_name || payload.hookEventName || "";

  if (event === "SessionStart") {
    try {
      const pdir = process.env.CLAUDE_PROJECT_DIR || process.env.SPEC_PROJECT_DIR || payload.cwd || process.cwd();
      // Same gate as PostToolUse: another tool's .specs/ gets no dev-spec status block in every session's context.
      if (!isDevSpecProject(pdir)) process.exit(0);
      const list = spec.listFeatures(pdir);
      if (!list.exists || !list.features.length) process.exit(0);
      const m = spec.msg(spec.projectLang(pdir));
      const h = m.hook;
      const phase = (p) => (m.phaseNames && m.phaseNames[p]) || p; // 'executing' → 'em execução' / 'en ejecución'
      // At most SESSION_MAX_FEATURES lines (150 features were ~8 KB of context in every session): the most relevant ones —
      // executing, then tasks-ready, then planning, complete last; ties by the latest spec activity (.state.json /
      // tasks.md mtime — ordering only, never a verdict) — printed in the usual order, then ONE "+N more" line.
      let shown = list.features;
      if (shown.length > SESSION_MAX_FEATURES) {
        const rank = (p) => (p === "executing" ? 0 : p === "tasks-ready" ? 1 : p === "complete" ? 3 : 2);
        const mtime = (f) => Math.max(...[".state.json", "tasks.md"].map((x) => { try { return fs.statSync(path.join(list.specsDir, f.name, x)).mtimeMs; } catch { return 0; } }));
        const keep = new Set(list.features.map((f) => ({ f, r: rank(f.phase), t: mtime(f) }))
          .sort((a, b) => a.r - b.r || b.t - a.t || (a.f.name < b.f.name ? -1 : 1)).slice(0, SESSION_MAX_FEATURES).map((x) => x.f));
        shown = list.features.filter((f) => keep.has(f));
      }
      const lines = shown.map((f) => h.sessionLine(f.name, f.tracks, phase(f.phase), f.tasksDone, f.tasks));
      if (shown.length < list.features.length && h.sessionMore) lines.push(h.sessionMore(list.features.length - shown.length));
      // Drift since finish (finished features only — a reopened one is not; archived ones are left to `dev-spec drift`,
      // like the feature lines above, so a set-aside feature can't nag every session). Bounded: over DRIFT_MAX_FILES
      // recorded files (or ~8 MB of them) nothing is hashed — `dev-spec drift` still checks on demand. Never blocks or
      // breaks the session line.
      try {
        const d = spec.drift(pdir, null, { maxFiles: DRIFT_MAX_FILES, maxBytes: 8 * 1024 * 1024, activeOnly: true });
        if (d && d.ok && !d.skipped) d.features.filter((x) => x.drifted).forEach((x) => lines.push(m.drift.hookLine(x.feature, x.changed.length + x.missing.length + x.nowPresent.length)));
      } catch { /* best-effort */ }
      // .specs/ from an older dev-spec (roadmap.json meta.specVersion absent or older than this engine — spec_init /
      // spec_create stamp a brand-new project, spec_upgrade {apply} stamps an upgraded one): ONE line pointing at the
      // upgrade audit. roadmap.json is already read (the project language); never throws.
      try {
        const v = spec.specVersionStatus(pdir);
        if (v && v.behind && m.upgrade) lines.push(m.upgrade.hookLine(v.from));
      } catch { /* best-effort */ }
      // 1.14 B4 — cross-feature file overlap: ONE line when two active features' open tasks plan the same files (or an active
      // feature plans files a finished one recorded in its drift baseline). Text reads only — nothing hashed; never throws.
      try {
        const ov = spec.featureOverlaps(pdir);
        if (ov && ov.pairs.length && m.forecast) {
          const names = ov.pairs.slice(0, 3).map((p) => p.a + (p.kind === "finished" ? " → " : " ↔ ") + p.b).join(", ") + (ov.pairs.length > 3 ? ", …" : "");
          lines.push(m.forecast.overlap.hookLine(ov.pairs.length, names));
        }
      } catch { /* best-effort */ }
      // 1.21 review A3 — the project's .gitattributes names the dev-spec-state merge driver, and git config's driver runs a script that
      // no longer exists or isn't this plugin's CLI (a plugin update moved the versioned plugin folder): git would keep only ours'
      // side of a .state.json both branches changed. ONE line. Text reads only (.gitattributes, the repository's config) — no git.
      try {
        const md = spec.mergeDriverStatus(pdir, { cli: path.join(__dirname, "..", "cli", "dev-spec.js") });
        if (md && md.named && (md.status === "missing" || md.status === "other") && m.mergeState && m.mergeState.hookLine) {
          lines.push(m.mergeState.hookLine(md.script || md.driver, md.status === "missing"));
        }
      } catch { /* best-effort */ }
      return emit("SessionStart", h.sessionHeader + "\n" + lines.join("\n"));
    } catch {
      process.exit(0);
    }
  }

  if (event === "PostToolUse") {
    const ti = payload.tool_input || payload.toolInput || {};
    const filePath = typeof ti.file_path === "string" ? ti.file_path : typeof ti.path === "string" ? ti.path : "";
    const fwd = filePath.replace(/\\/g, "/");
    if (!filePath || !fwd.includes("/.specs/")) process.exit(0);
    // Subagent-execution scratch (briefs, reports, ledger) is not spec content: no lint, no roadmap churn.
    if (fwd.includes("/.execution/")) process.exit(0);
    // A feature folder being removed (renamed to a `.removing-*` tombstone first) is no spec any more.
    if (fwd.includes("/.specs/.removing-")) process.exit(0);
    // A network file path (\\host\share\…, //host/share/…, \\?\UNC\…) names a host the agent chose: nothing below stats it unless
    // it lies — as text — inside the session's own folder on that share (CLAUDE_PROJECT_DIR / SPEC_PROJECT_DIR / the payload's
    // cwd, Claude Code's own), or that folder inside the file's project — a project living on a share keeps its checks
    // (1.16 verify NEW-3; spec.networkPathInside reads no file).
    if (spec.isNetworkPath(filePath)) {
      const own = [process.env.CLAUDE_PROJECT_DIR, process.env.SPEC_PROJECT_DIR, payload.cwd]
        .filter((v) => typeof v === "string" && v.trim() && !/^\$\{[^}]*\}$/.test(v.trim())).map((v) => v.trim());
      const proj = findProjectDir(filePath);
      if (!own.some((d) => spec.networkPathInside(d, filePath) != null || spec.networkPathInside(proj, d) != null)) process.exit(0);
    }
    // Project templates (.specs/templates/[<lang>/]requirements.md …) are no feature's spec: never linted as one (a
    // .specs/templates/pt/design.md is not feature 'pt''s design) and no roadmap churn — `dev-spec templates check` checks them.
    // (A FEATURE named templates created before 1.14 — its folder holds a .state.json — is still a feature.)
    const tplAt = fwd.match(/^(.*\/\.specs)\/templates\//i);
    if (tplAt && !fs.existsSync(path.join(tplAt[1], "templates", ".state.json"))) process.exit(0);
    // Track packs (.specs/tracks/<name>/requirements.md …, 1.15) are no feature's spec either — `dev-spec tracks check` checks them.
    // (A FEATURE named tracks created before 1.15 — its folder holds a .state.json — is still a feature.)
    const packAt = fwd.match(/^(.*\/\.specs)\/tracks\//i);
    if (packAt && !fs.existsSync(path.join(packAt[1], "tracks", ".state.json"))) process.exit(0);
    const base = path.basename(filePath).toLowerCase();
    const pdir = findProjectDir(filePath);
    if (!isDevSpecProject(pdir)) process.exit(0);

    const feature = path.basename(path.dirname(filePath));
    // 1.22 review: a tasks.md / change.md saved by hand (a box ticked with the Edit tool) is activity the stop gate must see —
    // stamped in the feature's .state.json (lastEditAt, under its lock), never read from a file date. Best-effort, silent.
    if (base === "tasks.md" || base === "change.md") {
      try { spec.recordSpecEdit(pdir, feature); } catch { /* best-effort */ }
    }
    const h = spec.msg(spec.featureLang(pdir, feature)).hook; // localized in the feature's language

    // Keep the roadmap current on any hand-edit of a spec file (not the roadmap files themselves).
    // The generated files at the .specs/ root (ROADMAP.md/.html, SPECS.md) are outputs, never a reason to refresh.
    const atRoot = path.resolve(path.dirname(filePath)).toLowerCase() === path.resolve(pdir, ".specs").toLowerCase();
    const generated = base === "roadmap.md" || base === "roadmap.html" || (atRoot && (base === "specs.md" || base === "upgrade.md"));
    let roadmapNote = "";
    if (!generated) {
      try {
        const w = spec.writeRoadmapMd(pdir);
        if (w.ok) roadmapNote = h.roadmapUpdated(w.overallPercent, w.complete, w.total);
      } catch {
        /* best-effort */
      }
      // …and the living catalog (.specs/SPECS.md) after a spec artifact changed — only once it exists and carries the
      // AUTO-GENERATED marker (maybeRefreshCatalog checks both; unchanged content is not rewritten). Steering is not
      // catalogued. Best-effort, silent.
      if (!/\/\.specs\/steering\//i.test(fwd)) {
        try { spec.maybeRefreshCatalog(pdir); } catch { /* best-effort */ }
      }
    }

    try {
      // The EARS lines of a criteria file — requirements.md, or a change's change.md (1.21 F5: its criteria AND its tasks; the
      // criteria view alone is linted — a task line is no criterion, the engine's own rule) — or null.
      const earsText = (fileName) => {
        const text = fs.readFileSync(filePath, "utf8");
        const lang = spec.featureLang(pdir, feature);
        const r = spec.earsValidate(fileName === "change.md" ? spec.changeViews(text).criteria : text, lang); // issue messages in the spec's language
        if (!r.ok) return null;
        const errs = r.issues.filter((i) => i.severity === "error");
        const warns = r.issues.filter((i) => i.severity === "warn");
        // Template placeholders anywhere in the file (Summary, stories, SC/NFR — not only criteria): never "all clean"
        // while any remain. The gates' own view: a removed track's [SaaS]/[AI] criteria are inactive.
        const ph = (spec.featurePlaceholders(pdir, feature, fileName) || { items: [] }).items;
        const G = spec.msg(lang).gates;
        // (1.21 verify V7: named after the file saved — a change's change.md is approved as the plan, it has no design)
        const phLine = ph.length ? G.hookPlaceholders(ph.length, ph.slice(0, 3).map((p) => `L${p.line} ${p.text.length > 40 ? p.text.slice(0, 39) + "…" : p.text}`).join(", ") + (ph.length > 3 ? ", " + G.more(ph.length - 3) : ""), fileName) : null;
        if (!errs.length && !warns.length) return phLine || h.earsClean(r.summary.criteriaDetected);
        // The severity label `dev-spec ears` prints (cliOutput.words: aviso / erro · aviso / error); EN keeps warn / error.
        const words = (spec.msg(lang).cliOutput && spec.msg(lang).cliOutput.words) || {};
        const top = [...errs, ...warns].slice(0, 6).map((i) => `  L${i.line} [${words[i.severity] || i.severity}] ${i.msg}`);
        return h.earsIssues(errs.length, warns.length, top.join("\n"), errs.length > 0, fileName) + (phLine ? "\n" + phLine : "");
      };
      // The trace lines of a feature's tasks — tasks.md, or a change's change.md — or null.
      const traceText = () => {
        const tr = spec.traceCheck(pdir, feature);
        if (!tr.ok) return null;
        // Every gap kind the engine reports, with its IDs (a hand-picked subset used to leave an empty "- ").
        const lang = spec.featureLang(pdir, feature);
        const parts = spec.traceGapLines(tr, lang);
        // Then the warnings (uncovered / phantom EC·NFR·SC) — listed, never blocking. No test-code scan here: hooks stay fast.
        const warns = spec.traceWarningLines(tr, lang);
        const warnText = warns.length ? "\n" + spec.msg(lang).deepTrace.warningsHead + "\n" + warns.map((w) => "  ▲ " + w).join("\n") : "";
        if (tr.verdict === "pass") return [h.traceOk(tr.totalAcs), ...parts.map((p) => "  - " + p)].join("\n") + warnText;
        return h.traceGaps(feature, (parts.length ? parts : [tr.verdict]).join("\n  - ")) + warnText;
      };
      if (base === "requirements.md") {
        const t = earsText("requirements.md");
        if (t == null) process.exit(0);
        return emit("PostToolUse", t);
      }

      if (base === "tasks.md") {
        const t = traceText();
        if (t == null) process.exit(0);
        return emit("PostToolUse", t);
      }

      if (base === "change.md") { // 1.21 F5 — a change: its one file holds the criteria and the tasks
        const t = [earsText("change.md"), traceText()].filter(Boolean);
        if (t.length) return emit("PostToolUse", t.join("\n"));
      }

      if (base === "design.md") {
        // The design's mandatory checks for the feature's ACTIVE tracks ([SaaS]/[AI] sections, Constitution Check,
        // placeholders) — one file, string checks only, in the feature's language.
        // Not an active feature's design (an archived one, steering/design.md): fall through to the roadmap note.
        const d = spec.designSaveCheck(pdir, feature);
        if (d.ok) return emit("PostToolUse", d.text);
      }
    } catch {
      process.exit(0);
    }
    // Not a requirements.md / tasks.md edit, but a spec file changed → surface the roadmap refresh.
    if (roadmapNote) return emit("PostToolUse", roadmapNote);
  }

  if (!emitted) process.exit(0);
}

// Never crash, whatever the payload: any unexpected error is a silent no-op.
function safeMain(raw) {
  try {
    main(raw);
  } catch {
    if (!emitted) process.exit(0);
  }
}

// Read the hook payload from stdin (cross-platform). Guard against no-stdin hangs.
let input = "";
if (process.stdin.isTTY) {
  safeMain("{}");
} else {
  process.stdin.setEncoding("utf8");
  process.stdin.on("data", (c) => (input += c));
  process.stdin.on("end", () => safeMain(input));
  process.stdin.on("error", () => process.exit(0));
  setTimeout(() => safeMain(input), 2000).unref(); // safety net
}
