#!/usr/bin/env node
"use strict";

/**
 * dev-spec-driven — local hook handler (zero-dependency).
 *
 * Wired from hooks/hooks.json for two events:
 *   - PostToolUse (Write|Edit): when a `.specs/.../requirements.md` is saved, lint EARS;
 *     when a `.specs/.../tasks.md` is saved, run a traceability check; when a `.specs/.../design.md`
 *     is saved, run its mandatory checks for the active tracks. Any spec edit also refreshes ROADMAP.md
 *     and, when it exists and is generated, the living catalog .specs/SPECS.md. Surfaces gaps in the
 *     moment, with zero CI and zero cost.
 *   - SessionStart: print a one-line status of all features in the project, plus one line per finished
 *     active feature whose implementing files drifted since finish (bounded; see DRIFT_MAX_FILES).
 *
 * It NEVER blocks: any error or irrelevant event exits 0 silently. Output is emitted as
 * `hookSpecificOutput.additionalContext` so Claude sees it as context, not as a user message.
 */

const fs = require("fs");
const path = require("path");

let spec;
try {
  spec = require(path.join(__dirname, "..", "mcp", "lib", "spec.js"));
} catch {
  process.exit(0); // engine not found — stay silent
}

let emitted = false;
let ran = false;
const DRIFT_MAX_FILES = 200; // SessionStart hashes at most this many recorded _Implements:_ files, else skips the drift check
// Emits exactly one JSON object and exits only after the write is flushed (Windows pipes truncate
// otherwise). Callers `return emit(...)` — nothing may call process.exit() after it.
function emit(eventName, text) {
  if (emitted) return;
  emitted = true;
  if (!text) process.exit(0);
  process.stdout.write(
    JSON.stringify({ hookSpecificOutput: { hookEventName: eventName, additionalContext: text } }),
    () => process.exit(0)
  );
}

// The hooks run in EVERY project. Only touch a .specs/ that dev-spec owns (another tool may use the name).
function isDevSpecProject(pdir) {
  const root = path.join(pdir, ".specs");
  if (fs.existsSync(path.join(root, "roadmap.json")) || fs.existsSync(path.join(root, "steering"))) return true;
  try {
    const rm = fs.readFileSync(path.join(root, "ROADMAP.md"), "utf8"); // generated by any dev-spec version
    if (/AUTO-GE(?:NERATED|RADO|NERADO) (?:by|por) dev-spec/.test(rm.slice(0, 4000))) return true;
  } catch { /* no roadmap */ }
  try {
    // .state.json (v1.9+) or classification.md (every spec_create) marks a dev-spec feature folder.
    return fs.readdirSync(root, { withFileTypes: true }).some((d) => d.isDirectory() &&
      (fs.existsSync(path.join(root, d.name, ".state.json")) || fs.existsSync(path.join(root, d.name, "classification.md"))));
  } catch {
    return false;
  }
}

function findProjectDir(filePath) {
  // Walk up from the file until we find the parent of a `.specs` directory.
  let dir = path.dirname(filePath);
  for (let i = 0; i < 12 && dir; i++) {
    if (path.basename(dir) === ".specs") return path.dirname(dir);
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return process.env.CLAUDE_PROJECT_DIR || process.env.SPEC_PROJECT_DIR || process.cwd();
}

function main(raw) {
  if (ran) return; // stdin 'end' and the safety-net timer must not both run the hook
  ran = true;
  // One hook event = one engine call: every spec file is read once across the steps below (roadmap, catalog, the
  // check), however many of them ask — the engine's own writes (ROADMAP.md, SPECS.md) keep that cache true.
  return spec.withReadCache(() => handle(raw));
}

function handle(raw) {
  let payload = {};
  try {
    payload = JSON.parse(raw || "{}");
  } catch {
    process.exit(0);
  }
  if (!payload || typeof payload !== "object") process.exit(0);
  const event = payload.hook_event_name || payload.hookEventName || "";

  if (event === "SessionStart") {
    try {
      const pdir = process.env.CLAUDE_PROJECT_DIR || process.env.SPEC_PROJECT_DIR || payload.cwd || process.cwd();
      const list = spec.listFeatures(pdir);
      if (!list.exists || !list.features.length) process.exit(0);
      const m = spec.msg(spec.projectLang(pdir));
      const h = m.hook;
      const phase = (p) => (m.phaseNames && m.phaseNames[p]) || p; // 'executing' → 'em execução' / 'en ejecución'
      const lines = list.features.map((f) => h.sessionLine(f.name, f.tracks, phase(f.phase), f.tasksDone, f.tasks));
      // Drift since finish (finished features only — a reopened one is not; archived ones are left to `dev-spec drift`,
      // like the feature lines above, so a set-aside feature can't nag every session). Bounded: over DRIFT_MAX_FILES
      // recorded files (or ~8 MB of them) nothing is hashed — `dev-spec drift` still checks on demand. Never blocks or
      // breaks the session line.
      try {
        const d = spec.drift(pdir, null, { maxFiles: DRIFT_MAX_FILES, maxBytes: 8 * 1024 * 1024, activeOnly: true });
        if (d && d.ok && !d.skipped) d.features.filter((x) => x.drifted).forEach((x) => lines.push(m.drift.hookLine(x.feature, x.changed.length + x.missing.length + x.nowPresent.length)));
      } catch { /* best-effort */ }
      return emit("SessionStart", h.sessionHeader + "\n" + lines.join("\n"));
    } catch {
      process.exit(0);
    }
  }

  if (event === "PostToolUse") {
    const ti = payload.tool_input || payload.toolInput || {};
    const filePath = typeof ti.file_path === "string" ? ti.file_path : typeof ti.path === "string" ? ti.path : "";
    const fwd = filePath.replace(/\\/g, "/");
    if (!filePath || !fwd.includes("/.specs/")) process.exit(0);
    // Subagent-execution scratch (briefs, reports, ledger) is not spec content: no lint, no roadmap churn.
    if (fwd.includes("/.execution/")) process.exit(0);
    const base = path.basename(filePath).toLowerCase();
    const pdir = findProjectDir(filePath);
    if (!isDevSpecProject(pdir)) process.exit(0);

    const feature = path.basename(path.dirname(filePath));
    const h = spec.msg(spec.featureLang(pdir, feature)).hook; // localized in the feature's language

    // Keep the roadmap current on any hand-edit of a spec file (not the roadmap files themselves).
    // The generated files at the .specs/ root (ROADMAP.md/.html, SPECS.md) are outputs, never a reason to refresh.
    const atRoot = path.resolve(path.dirname(filePath)).toLowerCase() === path.resolve(pdir, ".specs").toLowerCase();
    const generated = base === "roadmap.md" || base === "roadmap.html" || (atRoot && base === "specs.md");
    let roadmapNote = "";
    if (!generated) {
      try {
        const w = spec.writeRoadmapMd(pdir);
        if (w.ok) roadmapNote = h.roadmapUpdated(w.overallPercent, w.complete, w.total);
      } catch {
        /* best-effort */
      }
      // …and the living catalog (.specs/SPECS.md) after a spec artifact changed — only once it exists and carries the
      // AUTO-GENERATED marker (maybeRefreshCatalog checks both; unchanged content is not rewritten). Steering is not
      // catalogued. Best-effort, silent.
      if (!/\/\.specs\/steering\//i.test(fwd)) {
        try { spec.maybeRefreshCatalog(pdir); } catch { /* best-effort */ }
      }
    }

    try {
      if (base === "requirements.md") {
        const text = fs.readFileSync(filePath, "utf8");
        const lang = spec.featureLang(pdir, feature);
        const r = spec.earsValidate(text, lang); // issue messages in the spec's language
        if (!r.ok) process.exit(0);
        const errs = r.issues.filter((i) => i.severity === "error");
        const warns = r.issues.filter((i) => i.severity === "warn");
        // Template placeholders anywhere in the file (Summary, stories, SC/NFR — not only criteria): never "all clean"
        // while any remain. The gates' own view: a removed track's [SaaS]/[AI] criteria are inactive.
        const ph = (spec.featurePlaceholders(pdir, feature, "requirements.md") || { items: [] }).items;
        const G = spec.msg(lang).gates;
        const phLine = ph.length ? G.hookPlaceholders(ph.length, ph.slice(0, 3).map((p) => `L${p.line} ${p.text.length > 40 ? p.text.slice(0, 39) + "…" : p.text}`).join(", ") + (ph.length > 3 ? ", " + G.more(ph.length - 3) : "")) : null;
        if (!errs.length && !warns.length) return emit("PostToolUse", phLine || h.earsClean(r.summary.criteriaDetected));
        const top = [...errs, ...warns].slice(0, 6).map((i) => `  L${i.line} [${i.severity}] ${i.msg}`);
        return emit("PostToolUse", h.earsIssues(errs.length, warns.length, top.join("\n"), errs.length > 0) + (phLine ? "\n" + phLine : ""));
      }

      if (base === "tasks.md") {
        const tr = spec.traceCheck(pdir, feature);
        if (!tr.ok) process.exit(0);
        // Every gap kind the engine reports, with its IDs (a hand-picked subset used to leave an empty "- ").
        const lang = spec.featureLang(pdir, feature);
        const parts = spec.traceGapLines(tr, lang);
        // Then the warnings (uncovered / phantom EC·NFR·SC) — listed, never blocking. No test-code scan here: hooks stay fast.
        const warns = spec.traceWarningLines(tr, lang);
        const warnText = warns.length ? "\n" + spec.msg(lang).deepTrace.warningsHead + "\n" + warns.map((w) => "  ▲ " + w).join("\n") : "";
        if (tr.verdict === "pass") return emit("PostToolUse", [h.traceOk(tr.totalAcs), ...parts.map((p) => "  - " + p)].join("\n") + warnText);
        return emit("PostToolUse", h.traceGaps(feature, (parts.length ? parts : [tr.verdict]).join("\n  - ")) + warnText);
      }

      if (base === "design.md") {
        // The design's mandatory checks for the feature's ACTIVE tracks ([SaaS]/[AI] sections, Constitution Check,
        // placeholders) — one file, string checks only, in the feature's language.
        // Not an active feature's design (an archived one, steering/design.md): fall through to the roadmap note.
        const d = spec.designSaveCheck(pdir, feature);
        if (d.ok) return emit("PostToolUse", d.text);
      }
    } catch {
      process.exit(0);
    }
    // Not a requirements.md / tasks.md edit, but a spec file changed → surface the roadmap refresh.
    if (roadmapNote) return emit("PostToolUse", roadmapNote);
  }

  if (!emitted) process.exit(0);
}

// Never crash, whatever the payload: any unexpected error is a silent no-op.
function safeMain(raw) {
  try {
    main(raw);
  } catch {
    if (!emitted) process.exit(0);
  }
}

// Read the hook payload from stdin (cross-platform). Guard against no-stdin hangs.
let input = "";
if (process.stdin.isTTY) {
  safeMain("{}");
} else {
  process.stdin.setEncoding("utf8");
  process.stdin.on("data", (c) => (input += c));
  process.stdin.on("end", () => safeMain(input));
  process.stdin.on("error", () => process.exit(0));
  setTimeout(() => safeMain(input), 2000).unref(); // safety net
}
