"use strict";

/**
 * dev-spec-driven engine — ROADMAP.md / .html, forecasts and overlaps.
 * The roadmap renderers (roadmapData is the shared computation), velocity and ETA forecasts, and cross-feature file
 * overlaps.
 *
 * Part of the engine behind mcp/lib/spec.js (the facade); the module rule is in engine/index.js.
 */
const path = require("path");
const i18n = require("../i18n.js");
// Owned by other engine modules — used at call time only; engine/index.js links them once every module has loaded.
let activeDesign, activeSectionTracks, activeTasks, chainPlaceholders, changedSinceApproval, clarificationMarkers,
  detectTracks, duplicateTaskNumbers, flatText, FOLD_CASE, globMatcher, implementsRel, isImplementsGlob, isObj,
  isRecord, MILESTONE_ICON, milestoneAttention, milestoneInvalidInfo, milestoneLine, milestoneStatuses, normalizeLang,
  ownRecord, parseTasks, PHASE_PERCENT, phaseActive, PHASES, readIfExists, readJson, readRoadmap, roadmap, roleWaitList,
  round1, round2, sectionState, specsRoot, SPIKE_FILE, spikeInfo, statePath, stats, supersedesTrace, taskBlocks,
  taskDepsWaitList, taskMarkers, taskMarkerSpans, taskProse, taskSchedule, timeOf, unverifiedLabel, verificationStatus,
  waiverView,
  featureSize, trackSectionReport, sectionVerdict;
function __link(E) { ({ activeDesign, activeSectionTracks, activeTasks, chainPlaceholders, changedSinceApproval,
  clarificationMarkers, detectTracks, duplicateTaskNumbers, flatText, FOLD_CASE, globMatcher, implementsRel,
  isImplementsGlob, isObj, isRecord, MILESTONE_ICON, milestoneAttention, milestoneInvalidInfo, milestoneLine,
  milestoneStatuses, normalizeLang, ownRecord, parseTasks, PHASE_PERCENT, phaseActive, PHASES, readIfExists, readJson,
  readRoadmap, roadmap, roleWaitList, round1, round2, sectionState, specsRoot, SPIKE_FILE, spikeInfo, statePath, stats,
  supersedesTrace, taskBlocks, taskDepsWaitList, taskMarkers, taskMarkerSpans, taskProse, taskSchedule, timeOf,
  unverifiedLabel, verificationStatus, waiverView,
  featureSize, trackSectionReport, sectionVerdict } = E); }

// ---------------------------------------------------------------------------
// ROADMAP.md renderer — a single always-current overview of all features
// ---------------------------------------------------------------------------

function progressBar(pct, n) {
  n = n || 10;
  const f = Math.max(0, Math.min(n, Math.round((pct / 100) * n)));
  return "▰".repeat(f) + "▱".repeat(n - f);
}

function mid(name) {
  return name.replace(/[^a-z0-9]/gi, "_");
}

// Localized chrome for the roadmap (the spec content itself is already in the user's language).
const ROADMAP_I18N = {
  en: { roadmap: "Roadmap", progress: "Progress", complete: "features complete", tasks: "tasks done", legend: "Legend", done: "done", inprogress: "in progress", blocked: "blocked", notstarted: "not started", nextup: "Next up", noFeatures: "No features yet.", allDone: "All features complete 🎉", nothingUnblocked: "Nothing unblocked — resolve the dependencies below.", features: "Features", colFeature: "Feature", colTracks: "Tracks", colPhase: "Phase", colTasks: "Tasks", colDeps: "Deps", colNext: "Next", deps: "Dependencies", noDeps: "No declared dependencies.", needs: "Needs attention", nothingFlagged: "Nothing flagged ✓", blockedBy: "blocked by", openClar: "open [NEEDS CLARIFICATION]", designTodo: "design has unfilled (TODO) sections", backlog: "Backlog (planned, not yet specced)", backlogEmpty: "(empty)", next: "next", ready: "ready to start", cycle: "Circular dependency", none: "(none)", unverified: "task(s) ticked without verification evidence", autogen: "AUTO-GENERATED by dev-spec — do not edit by hand.", theme: "Theme" },
  pt: { roadmap: "Roadmap", progress: "Progresso", complete: "features completas", tasks: "tasks feitas", legend: "Legenda", done: "feito", inprogress: "em curso", blocked: "bloqueada", notstarted: "por começar", nextup: "A seguir", noFeatures: "Ainda sem features.", allDone: "Todas as features completas 🎉", nothingUnblocked: "Nada desbloqueado — resolve as dependências abaixo.", features: "Features", colFeature: "Feature", colTracks: "Tracks", colPhase: "Fase", colTasks: "Tasks", colDeps: "Deps", colNext: "Próxima", deps: "Dependências", noDeps: "Sem dependências declaradas.", needs: "Precisa de atenção", nothingFlagged: "Nada a assinalar ✓", blockedBy: "bloqueada por", openClar: "[NEEDS CLARIFICATION] por resolver", designTodo: "design com secções por preencher (TODO)", backlog: "Backlog (planeadas, ainda sem spec)", backlogEmpty: "(vazio)", next: "próxima", ready: "pronta para começar", cycle: "Dependência circular", none: "(nenhuma)", unverified: "tarefa(s) marcada(s) sem evidência de verificação", autogen: "AUTO-GERADO por dev-spec — não editar à mão.", theme: "Tema" },
  es: { roadmap: "Hoja de ruta", progress: "Progreso", complete: "funciones completas", tasks: "tareas hechas", legend: "Leyenda", done: "hecho", inprogress: "en curso", blocked: "bloqueada", notstarted: "sin empezar", nextup: "A continuación", noFeatures: "Aún sin funciones.", allDone: "Todas las funciones completas 🎉", nothingUnblocked: "Nada desbloqueado — resuelve las dependencias.", features: "Funciones", colFeature: "Función", colTracks: "Tracks", colPhase: "Fase", colTasks: "Tareas", colDeps: "Deps", colNext: "Siguiente", deps: "Dependencias", noDeps: "Sin dependencias declaradas.", needs: "Necesita atención", nothingFlagged: "Nada que señalar ✓", blockedBy: "bloqueada por", openClar: "[NEEDS CLARIFICATION] sin resolver", designTodo: "diseño con secciones sin rellenar (TODO)", backlog: "Backlog (planificadas, aún sin spec)", backlogEmpty: "(vacío)", next: "siguiente", ready: "lista para empezar", cycle: "Dependencia circular", none: "(ninguna)", unverified: "tarea(s) marcada(s) sin evidencia de verificación", autogen: "AUTO-GENERADO por dev-spec — no editar a mano.", theme: "Tema" },
};
// "planned": broken into tasks, none done yet — 30% of the way, so ⬜ "not started" next to it read as a contradiction.
Object.entries({ en: "planned", pt: "planeada", es: "planificada" }).forEach(([l, s]) => { ROADMAP_I18N[l].planned = s; });
// What the gates flag (1.13): "needs attention" lines and the marker for a next task that is still only a placeholder.
Object.entries({
  en: { sections: "mandatory sections missing/unfilled", placeholders: "template placeholders in the current phase", changedSince: "changed since approval — re-review", forced: "approved with --force (checks were failing)", placeholderTask: "(placeholder)" },
  pt: { sections: "secções obrigatórias em falta/por preencher", placeholders: "placeholders do template na fase atual", changedSince: "alterado desde a aprovação — rever de novo", forced: "aprovado com --force (havia verificações a falhar)", placeholderTask: "(por preencher)" },
  es: { sections: "secciones obligatorias que faltan/sin rellenar", placeholders: "placeholders de la plantilla en la fase actual", changedSince: "modificado desde la aprobación — revisar de nuevo", forced: "aprobado con --force (había verificaciones fallando)", placeholderTask: "(sin rellenar)" },
}).forEach(([l, o]) => Object.assign(ROADMAP_I18N[l], o));
// pt-BR (1.14 D1) is derived from pt like every i18n table (i18n.derivePtBr), plus the labels a word map can't get right.
// Derived on first use (a lazy getter, as in i18n.js): loading the engine never pays for a locale it doesn't render.
let ROADMAP_PT_BR = null;
Object.defineProperty(ROADMAP_I18N, "pt-BR", { enumerable: true, get: () => ROADMAP_PT_BR ||
  (ROADMAP_PT_BR = Object.assign(i18n.derivePtBr(ROADMAP_I18N.pt), { notstarted: "não iniciada", nothingFlagged: "Nada a sinalizar ✓" })) });
function i18nLang(lang) {
  return ROADMAP_I18N[normalizeLang(lang)] || ROADMAP_I18N.en;
}
function htmlEsc(s) {
  return String(s == null ? "" : s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;");
}
function cleanTaskText(t) {
  return String(t || "").replace(/^(?:\[[^\]]*\]\s*)+/, "");
}

// 1.22 review — the per-feature ROW cache (in process: the MCP server refreshes ROADMAP.md after every tick, and on 30 features ×
// 40 tasks a tick took 313 ms against 13.8 without the refresh). A row is recomputed unless every input it reads is unchanged:
// the feature's folder (each entry's size, mtime, ctime and inode — `.history/` one level down; `.execution/`, the lock and
// temp files are scratch), the project inputs (roadmap.json, steering/, templates/, tracks/ — two levels), the feature's
// roadmap view (`f`, its overlaps). A file stamped within ROW_OPTS.racyMs (3 s) of now (mtime or ctime) is never trusted — git's
// "racy" rule: a coarse file system clock can give two writes of the same size one stamp —, and a row whose answer depends
// on the date (a spike's timebox, a waiver's expiry) is never stored. Bounded (ROW_CACHE_MAX). ROADMAP.md / .html stay byte
// for byte what a fresh computation writes (mcp/tests/08-tasks.js compares them).
const fs = require("fs");
const ROW_CACHE = new Map();
const ROW_CACHE_MAX = 500;
const ROW_CALLS = { n: 0, hits: 0 }; // roadmapData calls in this process; rows served from the cache
const ROW_OPTS = { racyMs: 3000 }; // the racy window (tests narrow it)
const ROW_SCRATCH = /^(?:\.execution|\.lock(?:\.reclaim)?|.*\.tmp)$/;
function rowStatSig(dir, depth, now, acc) {
  let ents;
  try { ents = fs.readdirSync(dir, { withFileTypes: true }); } catch { acc.push("-"); return; }
  ents.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  for (const e of ents.slice(0, 400)) {
    if (ROW_SCRATCH.test(e.name)) continue;
    const p = path.join(dir, e.name);
    let s;
    try { s = fs.statSync(p); } catch { acc.push(e.name + ":?"); continue; }
    if (Math.max(s.mtimeMs, s.ctimeMs) > now - ROW_OPTS.racyMs) acc.racy = true;
    acc.push(e.name + ":" + (s.isDirectory() ? "d" : s.size) + ":" + s.mtimeMs + ":" + s.ctimeMs + ":" + s.ino);
    if (s.isDirectory() && depth > 0) { acc.push("{"); rowStatSig(p, depth - 1, now, acc); acc.push("}"); }
  }
  if (ents.length > 400) acc.racy = true; // too many to sign: never trusted
}
function rowProjectSig(root, now) {
  const acc = [];
  for (const f of ["roadmap.json"]) { try { const s = fs.statSync(path.join(root, f)); if (Math.max(s.mtimeMs, s.ctimeMs) > now - ROW_OPTS.racyMs) acc.racy = true; acc.push(f + ":" + s.size + ":" + s.mtimeMs + ":" + s.ctimeMs + ":" + s.ino); } catch { acc.push(f + ":-"); } }
  for (const d of ["steering", "templates", "tracks"]) { acc.push(d + "{"); rowStatSig(path.join(root, d), 2, now, acc); acc.push("}"); }
  return { sig: acc.join("\n"), racy: !!acc.racy };
}
// Shared computation for both renderers. opts.now: "today" for the forecasts (tests).
function roadmapData(projectDir, opts = {}) {
  const rmv = roadmapExtras(projectDir, roadmap(projectDir), opts); // + velocity, each feature's forecast, overlaps
  const root = specsRoot(projectDir);
  let tasksDone = 0;
  let tasksTotal = 0;
  const now = Date.now();
  // The first call of a process signs nothing: a one-shot process (the CLI, a hook) never calls twice, and the stats would only
  // add to its time; a long-lived one (the MCP server) caches from its second refresh on.
  const sign = ROW_CALLS.n++ > 0;
  const proj = sign ? rowProjectSig(root, now) : null;
  const rows = rmv.features.map((f) => {
    const dir = path.join(root, f.name);
    if (!proj) {
      const row = roadmapRow(projectDir, dir, f, rmv);
      tasksDone += row.done;
      tasksTotal += row.total;
      return row;
    }
    const acc = [];
    rowStatSig(dir, 1, now, acc);
    const key = path.resolve(dir) + "\n" + JSON.stringify(f) + "\n" + JSON.stringify((rmv.overlaps || []).filter((p) => p.a === f.name)) + "\n" + proj.sig + "\n" + acc.join("\n");
    const hit = !proj.racy && !acc.racy ? ROW_CACHE.get(path.resolve(dir)) : undefined;
    let row;
    if (hit && hit.key === key) { row = hit.row; ROW_CALLS.hits++; }
    else {
      row = roadmapRow(projectDir, dir, f, rmv);
      if (!proj.racy && !acc.racy && f.kind !== "spike" && !Object.keys(row.waivers).length) {
        if (ROW_CACHE.size >= ROW_CACHE_MAX) ROW_CACHE.clear();
        ROW_CACHE.set(path.resolve(dir), { key, row });
      } else ROW_CACHE.delete(path.resolve(dir));
    }
    tasksDone += row.done;
    tasksTotal += row.total;
    return row;
  });
  return { rmv, rows, tasksDone, tasksTotal };
}
// One feature's row of roadmapData (what the renderers read; f: its roadmap() view). Pure on its inputs (rowStatSig's).
function roadmapRow(projectDir, dir, f, rmv) {
  {
    const raw = { "requirements.md": readIfExists(path.join(dir, "requirements.md")), "design.md": readIfExists(path.join(dir, "design.md")), "tasks.md": readIfExists(path.join(dir, "tasks.md")) };
    const reqs = raw["requirements.md"] || "";
    const design = raw["design.md"] || "";
    const clar = clarificationMarkers(reqs).length;
    const tracks = detectTracks(dir);
    const designTodo = /^>\s*\*\*TODO\*\*/m.test(activeDesign(design, tracks));
    const tasks = parseTasks(activeTasks(raw["tasks.md"], tracks));
    const done = tasks.filter((t) => t.done).length;
    const sch = taskSchedule(taskBlocks(activeTasks(raw["tasks.md"], tracks) || "")); // 1.14 F3: next_task's rule
    const next = sch.next;
    // Open tasks, none of which can start (a cycle, a _Depends:_ naming no task): shown blocked, never "ready" (review R7).
    const depsBlocked = !next && done < tasks.length ? (sch.blocked.length ? sch.blocked : sch.skipped) : null;
    // The icon agrees with the percent: past the requirements (16–25% = design / test / eval plan) a feature is in
    // progress — ⬜ 'not started' only below that; tasks-ready (30%, nothing done) is 📋 planned.
    const state = f.percent === 100 ? "done" : f.blocked ? "blocked" : done > 0 || f.phase === "executing" ? "inprogress"
      : f.phase === "tasks-ready" ? "planned" : f.percent > PHASE_PERCENT.requirements ? "inprogress" : "notstarted";
    // The per-task detail (reason codes), not just a count: the attention line names each task and why, as doctor does.
    const { unverifiedDetail } = verificationStatus(projectDir, f.name, dir);
    const unverified = unverifiedDetail.length;
    // What the gates flag, per feature: missing/unfilled mandatory sections, artifacts edited after their approval,
    // the current phase's template placeholders, approvals recorded with --force.
    const st = readJson(statePath(dir)).data; // read-only here: no resolver pass (it re-reads roadmap.json per call)
    const approvals = isObj(st) && isObj(st.approvals) ? st.approvals : {};
    // 1.21 F5: the size's rules and the stricter filled rule (a guidance-only section on an approved design is flagged too — a warn)
    const size = featureSize(dir);
    const sections = trackSectionReport(design, tracks, { size, lang: isObj(st) && typeof st.lang === "string" ? st.lang : undefined })
      .flatMap(([, mark, rows]) => rows.filter((s) => sectionVerdict(s, { size }) !== "pass").map((s) => ({ ...s, mark })));
    const changed = changedSinceApproval(dir, approvals, tracks, isObj(st) ? st.kind : undefined);
    const placeholders = chainPlaceholders(dir, tracks, (isObj(st) && st.kind) || "feature", f.phase, true, raw).blocking.map((r) => r.file);
    const forced = PHASES.filter((p) => phaseActive(p, tracks) && approvals[p] && approvals[p].forced);
    // 1.16 U3: the waivers of those forced approvals (reason, expiry, expired) — the attention line shows them
    const waivers = Object.fromEntries(forced.map((p) => [p, waiverView(approvals[p].waiver)]).filter(([, w]) => w));
    const overlaps = (rmv.overlaps || []).filter((p) => p.a === f.name); // its side of each cross-feature file overlap
    const roleWait = roleWaitList(projectDir, dir, st, tracks); // 1.14 B3: sign-off rounds under way (some roles signed, some not)
    const spikeTimebox = f.kind === "spike" ? spikeInfo(dir).timeboxPassed : null; // 1.14 C2: a spike past its timebox with no decision
    return { f, clar, done, total: tasks.length, next, depsBlocked, designTodo, state, unverified, unverifiedDetail, sections, changed, placeholders, forced, waivers, overlaps, roleWait, spikeTimebox };
  }
}

function buildAttention(rows, t, lang) {
  const fm = i18n.msg(lang);
  const a = [];
  rows.forEach((r) => {
    if (r.f.blocked) a.push({ name: r.f.name, msg: `${t.blockedBy} ${r.f.unmetDeps.join(", ")}` });
    if (r.depsBlocked && r.depsBlocked.length) a.push({ name: r.f.name, msg: fm.taskDeps.roadmapBlocked(taskDepsWaitList(r.depsBlocked, lang)) }); // 1.14 F3
    if (r.clar) a.push({ name: r.f.name, msg: `${r.clar} ${t.openClar}` });
    // The named sections say more than "design has unfilled (TODO) sections" — that line stays for a TODO elsewhere.
    if (r.sections && r.sections.length) {
      a.push({ name: r.f.name, msg: `${t.sections}: ${r.sections.map((s) => `${s.mark} ${fm.sectionNames[s.section] || s.section} (${fm.sectionStatus[s.status] || s.status})`).join(", ")}` });
    } else if (r.designTodo) a.push({ name: r.f.name, msg: t.designTodo });
    if (r.placeholders && r.placeholders.length) a.push({ name: r.f.name, msg: `${t.placeholders}: ${r.placeholders.join(", ")}` });
    if (r.changed && r.changed.length) a.push({ name: r.f.name, msg: `${t.changedSince}: ${r.changed.join(", ")}` });
    // a forced approval with its waiver (1.16 U3): "design (waiver: <reason>, until 2026-12-31)" — an expired one reads EXPIRED
    if (r.forced && r.forced.length) a.push({ name: r.f.name, msg: `${t.forced}: ${r.forced.map((p) => (r.waivers && r.waivers[p] ? fm.waiver.roadmapItem(p, r.waivers[p].reason, r.waivers[p].expires, r.waivers[p].expired) : p)).join(", ")}` });
    if (r.roleWait && r.roleWait.length) a.push({ name: r.f.name, msg: fm.governance.roadmapAwaiting(r.roleWait.map((w) => `${w.phase} (${w.missing.join(", ")})`).join(", ")) }); // 1.14 B3
    // "2 task(s) ticked without verification evidence: #1 (latest run failed), #3" — the same localized per-task
    // reasons doctor and spec_finish give (unverifiedLabel; no-evidence needs no label), in the roadmap's language.
    if (r.unverified) a.push({ name: r.f.name, msg: `${r.unverified} ${t.unverified}: ${unverifiedLabel({ unverifiedDetail: r.unverifiedDetail || [] }, lang)}` });
    for (const p of r.overlaps || []) a.push({ name: r.f.name, msg: overlapAttention(p, lang) }); // cross-feature file overlap
    if (r.spikeTimebox) a.push({ name: r.f.name, msg: fm.spike.roadmapTimebox(r.spikeTimebox) }); // 1.14 C2
  });
  return a;
}
// A roadmap "next" cell: the task text without its tags — or a localized marker when nothing but a template
// placeholder is left ("#1 " with an empty text used to be shown).
function roadmapTaskText(text, t) {
  const s = cleanTaskText(text).trim();
  return s ? s : t.placeholderTask;
}

// `data`: a roadmapData() result to render (one computation for the MD and the HTML refresh).
// The Phase column in the roadmap's language (detectPhase() tokens stay English in roadmap.json and every JSON result).
function roadmapPhaseName(lang) {
  const P = i18n.msg(lang).phaseNames || {};
  return (phase) => (Object.prototype.hasOwnProperty.call(P, phase) ? P[phase] : phase);
}

function renderRoadmapMd(projectDir, lang, data) {
  const t = i18nLang(lang);
  const phaseName = roadmapPhaseName(lang);
  const { rmv, rows, tasksDone, tasksTotal } = data || roadmapData(projectDir);
  const proj = path.basename(path.resolve(projectDir));
  const icon = { done: "✅", inprogress: "🟡", blocked: "⛔", planned: "📋", notstarted: "⬜" };
  const attention = buildAttention(rows, t, lang).concat(milestoneAttention(rmv.milestones, lang, rmv.milestonesInvalid)); // + late / at-risk / invalid milestones (1.16 E3)
  const cell = (s) => String(s).replace(/\|/g, "\\|").replace(/\r?\n/g, " ");
  const depsCell = (f) => (f.dependsOn.length ? f.dependsOn.map((d) => d + (f.unmetDeps.includes(d) ? " ✗" : " ✓")).join(", ") : "—");
  const nextCell = (r) => (r.f.percent === 100 ? "—" : r.f.blocked || r.depsBlocked ? t.blocked : r.next ? `#${r.next.number} ${cell(roadmapTaskText(r.next.text, t).slice(0, 42))}` : "…");
  const nextUp = rows.filter((r) => r.f.percent < 100 && !r.f.blocked && !r.depsBlocked);
  const kindTag = (f) => (f.kind === "spike" ? " 🔬 " + i18n.msg(lang).spike.kind : ""); // 1.14 C2: spikes read apart
  const specLink = (f) => `./${f.name}/${f.kind === "spike" ? SPIKE_FILE : f.kind === "change" ? "change.md" : "requirements.md"}`; // 1.21 F5: a change's one file

  let md = `# ${t.roadmap} — ${proj}\n\n<!-- ${t.autogen} -->\n\n`;
  md += `**${t.progress}: ${rmv.overallPercent}%** ${progressBar(rmv.overallPercent)} · ${rmv.complete}/${rmv.total} ${t.complete} · ${tasksDone}/${tasksTotal} ${t.tasks}\n\n`;
  if (rows.length) md += `_${velocityText(rmv.velocity, lang)}_\n\n`; // forecasts: the project velocity (or "not enough data")
  md += `${t.legend}: ✅ ${t.done} · 🟡 ${t.inprogress} · ⛔ ${t.blocked} · 📋 ${t.planned} · ⬜ ${t.notstarted}\n`;
  if (rmv.cycle) md += `\n> ⚠ **${t.cycle}:** ${rmv.cycle.join(" → ")}\n`;

  md += `\n## ▶ ${t.nextup}\n`;
  if (!rmv.features.length) md += `_${t.noFeatures}_\n`;
  else if (!nextUp.length) md += rmv.complete === rmv.total ? `${t.allDone}\n` : `_${t.nothingUnblocked}_\n`;
  else nextUp.slice(0, 3).forEach((r) => (md += `- **${r.f.name}**${kindTag(r.f)} (${r.f.tracks}) — ${r.next ? t.next + " " + nextCell(r) : t.ready}\n`));

  md += `\n## ${t.features}\n\n`;
  if (!rows.length) md += `_${t.none}_\n`;
  else {
    const F = i18n.msg(lang).forecast;
    md += `| | ${t.colFeature} | ${t.colTracks} | ${t.colPhase} | % | ${t.colTasks} | ${t.colDeps} | ${t.colNext} | ${F.colEta} |\n|---|---|---|---|---|---|---|---|---|\n`;
    for (const r of rows) md += `| ${icon[r.state]} | [${r.f.name}](${specLink(r.f)})${kindTag(r.f)} | ${r.f.tracks} | ${phaseName(r.f.phase)} | ${r.f.percent}% | ${r.done}/${r.total} | ${depsCell(r.f)} | ${nextCell(r)} | ${etaText(r.f.forecast, lang) || "—"} |\n`;
    if (rows.some((r) => r.f.forecast && r.f.forecast.eta)) md += `\n${F.etaNote(Math.round(FORECAST_SPREAD * 100))}\n`;
  }

  if ((rmv.milestones || []).length) { // 1.16 E3 — each milestone: its date vs the latest ETA of its open features
    const MS = i18n.msg(lang).milestone;
    md += `\n## 🏁 ${MS.title}\n\n| ${MS.cols.join(" | ")} |\n|${MS.cols.map(() => "---").join("|")}|\n`;
    for (const m of rmv.milestones) {
      const feats = m.features.join(", ") + (m.archived ? ` (${MS.archivedLabel}: ${m.archived.join(", ")})` : "");
      md += `| ${cell(m.name)} | ${cell(m.date)} | ${cell(feats || "—")} | ${m.done}/${m.total} | ${cell(m.eta || "—")} | ${MILESTONE_ICON[m.status]} ${MS.status[m.status]} |\n`; // every stored value through cell() (1.16 E review M2)
    }
  }

  md += `\n## ${t.deps}\n\n`;
  const edges = rmv.features.flatMap((f) => f.dependsOn.map((d) => `  ${mid(d)}["${d}"] --> ${mid(f.name)}["${f.name}"]`));
  md += edges.length ? "```mermaid\ngraph LR\n" + [...new Set(edges)].join("\n") + "\n```\n" : `_${t.noDeps}_\n`;

  md += `\n## ⚠ ${t.needs}\n\n`;
  md += attention.length ? attention.map((a) => `- **${a.name}** — ${a.msg}`).join("\n") + "\n" : `_${t.nothingFlagged}_\n`;

  md += `\n## ${t.backlog}\n\n`;
  md += rmv.backlog.length ? rmv.backlog.map((b) => `- [ ] **${flatText(b.name)}**${b.note ? " — " + flatText(b.note) : ""}`).join("\n") + "\n" : `_${t.backlogEmpty}_\n`;
  return md;
}

// Self-contained HTML — brand palette (Pro Digital Key), system-default + toggle, zero dependencies.
function renderRoadmapHtml(projectDir, lang, data) {
  const t = i18nLang(lang);
  const phaseName = roadmapPhaseName(lang);
  const langAttr = normalizeLang(lang); // en | pt | es | pt-BR — a valid BCP 47 tag
  const { rmv, rows, tasksDone, tasksTotal } = data || roadmapData(projectDir);
  const proj = path.basename(path.resolve(projectDir));
  const attention = buildAttention(rows, t, lang).concat(milestoneAttention(rmv.milestones, lang, rmv.milestonesInvalid)); // + late / at-risk / invalid milestones (1.16 E3)
  const dot = { done: "var(--c-done)", inprogress: "var(--c-prog)", blocked: "var(--c-block)", planned: "var(--accent)", notstarted: "var(--c-muted)" };
  const label = { done: t.done, inprogress: t.inprogress, blocked: t.blocked, planned: t.planned, notstarted: t.notstarted };
  const nextUp = rows.filter((r) => r.f.percent < 100 && !r.f.blocked && !r.depsBlocked);
  const nextTxt = (r) => (r.f.percent === 100 ? "—" : r.f.blocked || r.depsBlocked ? t.blocked : r.next ? `#${r.next.number} ${htmlEsc(roadmapTaskText(r.next.text, t).slice(0, 60))}` : "…");

  const featRows = rows
    .map(
      (r) =>
        `<tr><td><span class="dot" style="background:${dot[r.state]}"></span></td>` +
        `<td><a href="./${encodeURI(r.f.name)}/${r.f.kind === "spike" ? SPIKE_FILE : r.f.kind === "change" ? "change.md" : "requirements.md"}">${htmlEsc(r.f.name)}</a>${r.f.kind === "spike" ? ` <span class="tracks">🔬 ${htmlEsc(i18n.msg(lang).spike.kind)}</span>` : ""}</td>` +
        `<td><span class="tracks">${htmlEsc(r.f.tracks)}</span></td>` +
        `<td>${htmlEsc(phaseName(r.f.phase))}</td>` +
        `<td class="pct"><span class="bar"><span style="width:${r.f.percent}%"></span></span>${r.f.percent}%</td>` +
        `<td>${r.done}/${r.total}</td>` +
        `<td>${r.f.dependsOn.length ? r.f.dependsOn.map((d) => `<span class="${r.f.unmetDeps.includes(d) ? "unmet" : "met"}">${htmlEsc(d)}</span>`).join(", ") : "—"}</td>` +
        `<td class="next">${nextTxt(r)}</td>` +
        `<td class="eta">${htmlEsc(etaText(r.f.forecast, lang) || "—")}</td></tr>`
    )
    .join("\n");
  const F = i18n.msg(lang).forecast;
  const anyEta = rows.some((r) => r.f.forecast && r.f.forecast.eta);
  const MS = i18n.msg(lang).milestone; // 1.16 E3 — the milestones table (only when some exist)
  const msRows = (rmv.milestones || []).map((m) => `<tr><td>${htmlEsc(m.name)}</td><td>${htmlEsc(m.date)}</td><td>${htmlEsc(m.features.join(", ") || "—")}${m.archived ? ` <span class="tracks">${htmlEsc(MS.archivedLabel)}: ${htmlEsc(m.archived.join(", "))}</span>` : ""}</td>` +
    `<td>${m.done}/${m.total}</td><td class="eta">${htmlEsc(m.eta || "—")}</td><td class="ms-${m.status}">${MILESTONE_ICON[m.status]} ${htmlEsc(MS.status[m.status])}</td></tr>`).join("\n");

  const depList = rmv.features.filter((f) => f.dependsOn.length).map((f) => `<li><b>${htmlEsc(f.name)}</b> ← ${f.dependsOn.map((d) => `<span class="${f.unmetDeps.includes(d) ? "unmet" : "met"}">${htmlEsc(d)}</span>`).join(", ")}</li>`).join("\n");
  const attList = attention.map((a) => `<li><b>${htmlEsc(a.name)}</b> — ${htmlEsc(a.msg)}</li>`).join("\n");
  const backList = rmv.backlog.map((b) => `<li><input type="checkbox" disabled> <b>${htmlEsc(b.name)}</b>${b.note ? " — " + htmlEsc(b.note) : ""}</li>`).join("\n");
  const nextCards = nextUp.slice(0, 3).map((r) => `<div class="card"><b>${htmlEsc(r.f.name)}${r.f.kind === "spike" ? " 🔬" : ""}</b><span class="tracks">${htmlEsc(r.f.tracks)}</span><div>${r.next ? t.next + " " + nextTxt(r) : t.ready}</div></div>`).join("\n");

  return `<!doctype html>
<html lang="${langAttr}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${t.roadmap} — ${htmlEsc(proj)}</title>
<style>
:root{ --brand:#11689B; --accent:#00AAFF; --accent2:#4A90E2;
  --bg:#040405; --bg2:#0A0A0C; --bg3:#121216; --text:#FFFFFF; --muted:#8A91A5; --border:rgba(74,144,226,.18);
  --c-done:#00e164; --c-prog:#FFD700; --c-block:#ff6b6b; --c-muted:#8A91A5; }
:root[data-theme="light"]{ --bg:#F8F9FA; --bg2:#FFFFFF; --bg3:#E9ECEF; --text:#1A1D20; --muted:#6C757D; --border:rgba(17,104,155,.18); --c-muted:#9aa3af; }
@media (prefers-color-scheme: light){ :root:not([data-theme]){ --bg:#F8F9FA; --bg2:#FFFFFF; --bg3:#E9ECEF; --text:#1A1D20; --muted:#6C757D; --border:rgba(17,104,155,.18); --c-muted:#9aa3af; } }
*{box-sizing:border-box} body{margin:0;background:var(--bg);color:var(--text);font-family:'Outfit',system-ui,-apple-system,Segoe UI,Roboto,sans-serif;line-height:1.5}
.wrap{max-width:1040px;margin:0 auto;padding:28px 20px 60px}
header{display:flex;align-items:center;gap:16px;flex-wrap:wrap;border-bottom:2px solid var(--brand);padding-bottom:14px}
h1{font-size:1.5rem;margin:0;font-weight:700} h1 small{color:var(--muted);font-weight:500;font-size:.85rem}
.spacer{flex:1}
.toggle{cursor:pointer;border:1px solid var(--border);background:var(--bg2);color:var(--text);border-radius:999px;padding:7px 14px;font:inherit;font-size:.85rem}
.toggle:hover{border-color:var(--brand)}
.prog{margin:18px 0 6px;font-weight:600}
.pbar{height:10px;border-radius:999px;background:var(--bg3);overflow:hidden;margin:8px 0}
.pbar>span{display:block;height:100%;background:linear-gradient(90deg,var(--brand),var(--accent))}
.sub{color:var(--muted);font-size:.9rem}
.legend{color:var(--muted);font-size:.85rem;margin:8px 0 4px;display:flex;gap:14px;flex-wrap:wrap}
.legend .dot{margin-right:5px}
h2{font-size:1.05rem;margin:28px 0 10px;color:var(--accent)}
.dot{display:inline-block;width:10px;height:10px;border-radius:50%;vertical-align:middle}
.cards{display:flex;gap:12px;flex-wrap:wrap}
.card{background:var(--bg2);border:1px solid var(--border);border-radius:12px;padding:12px 14px;min-width:220px}
.card b{display:block;margin-bottom:4px} .tracks{display:inline-block;font-size:.72rem;font-weight:500;color:var(--accent2);background:rgba(74,144,226,.12);border:1px solid var(--border);padding:2px 9px;border-radius:8px;margin:3px 0;white-space:nowrap}
table{width:100%;border-collapse:collapse;font-size:.9rem;background:var(--bg2);border:1px solid var(--border);border-radius:12px;overflow:hidden}
th,td{text-align:left;padding:9px 11px;border-bottom:1px solid var(--border)} th{color:var(--muted);font-weight:600;font-size:.78rem;text-transform:uppercase;letter-spacing:.04em}
tr:last-child td{border-bottom:none} a{color:var(--accent);text-decoration:none} a:hover{text-decoration:underline}
.pct{white-space:nowrap} .pct .bar{display:inline-block;width:54px;height:6px;border-radius:999px;background:var(--bg3);vertical-align:middle;margin-right:7px;overflow:hidden}
.pct .bar>span{display:block;height:100%;background:var(--brand)} .next{color:var(--muted)} .eta{white-space:nowrap}
.met{color:var(--c-done)} .unmet{color:var(--c-block)} .ms-late{color:var(--c-block)} .ms-at-risk{color:var(--c-prog)} .ms-done{color:var(--c-done)}
ul{list-style:none;padding:0;margin:0} li{padding:5px 0;border-bottom:1px solid var(--border)} li:last-child{border:none}
footer{margin-top:36px;color:var(--muted);font-size:.78rem;border-top:1px solid var(--border);padding-top:12px}
</style>
</head>
<body><div class="wrap">
<header>
  <h1>${t.roadmap} <small>— ${htmlEsc(proj)}</small></h1>
  <span class="spacer"></span>
  <button class="toggle" id="tg" aria-label="${t.theme}">◐ ${t.theme}</button>
</header>

<div class="prog">${t.progress}: ${rmv.overallPercent}%</div>
<div class="pbar"><span style="width:${rmv.overallPercent}%"></span></div>
<div class="sub">${rmv.complete}/${rmv.total} ${t.complete} · ${tasksDone}/${tasksTotal} ${t.tasks}</div>
${rows.length ? `<div class="sub">${htmlEsc(velocityText(rmv.velocity, lang))}</div>` : ""}
<div class="legend">
  <span><span class="dot" style="background:var(--c-done)"></span>${t.done}</span>
  <span><span class="dot" style="background:var(--c-prog)"></span>${t.inprogress}</span>
  <span><span class="dot" style="background:var(--c-block)"></span>${t.blocked}</span>
  <span><span class="dot" style="background:var(--accent)"></span>${t.planned}</span>
  <span><span class="dot" style="background:var(--c-muted)"></span>${t.notstarted}</span>
</div>
${rmv.cycle ? `<p class="unmet">⚠ ${t.cycle}: ${htmlEsc(rmv.cycle.join(" → "))}</p>` : ""}

<h2>▶ ${t.nextup}</h2>
${!rmv.features.length ? `<p class="sub">${t.noFeatures}</p>` : !nextUp.length ? `<p class="sub">${rmv.complete === rmv.total ? t.allDone : t.nothingUnblocked}</p>` : `<div class="cards">${nextCards}</div>`}

<h2>${t.features}</h2>
${rows.length ? `<table><thead><tr><th></th><th>${t.colFeature}</th><th>${t.colTracks}</th><th>${t.colPhase}</th><th>%</th><th>${t.colTasks}</th><th>${t.colDeps}</th><th>${t.colNext}</th><th>${htmlEsc(F.colEta)}</th></tr></thead><tbody>${featRows}</tbody></table>` : `<p class="sub">${htmlEsc(t.none)}</p>`}${anyEta ? `\n<p class="sub">${htmlEsc(F.etaNote(Math.round(FORECAST_SPREAD * 100)))}</p>` : ""}

${msRows ? `<h2>🏁 ${htmlEsc(MS.title)}</h2>\n<table><thead><tr>${MS.cols.map((c) => `<th>${htmlEsc(c)}</th>`).join("")}</tr></thead><tbody>${msRows}</tbody></table>\n\n` : ""}<h2>${t.deps}</h2>
${depList ? `<ul>${depList}</ul>` : `<p class="sub">${t.noDeps}</p>`}

<h2>⚠ ${t.needs}</h2>
${attList ? `<ul>${attList}</ul>` : `<p class="sub">${t.nothingFlagged}</p>`}

<h2>${t.backlog}</h2>
${backList ? `<ul>${backList}</ul>` : `<p class="sub">${t.backlogEmpty}</p>`}

<footer>${t.autogen}</footer>
</div>
<script>
(function(){
  var k="dev-spec-theme", b=document.getElementById("tg"), r=document.documentElement;
  var s=localStorage.getItem(k); if(s) r.setAttribute("data-theme", s);
  b.addEventListener("click", function(){
    var cur=r.getAttribute("data-theme");
    if(!cur){ cur = matchMedia("(prefers-color-scheme: light)").matches ? "light" : "dark"; }
    var nx = cur==="light" ? "dark" : "light";
    r.setAttribute("data-theme", nx); localStorage.setItem(k, nx);
  });
})();
</script>
</body>
</html>
`;
}

// ---------------------------------------------------------------------------
// Roadmap forecasts (1.14). A task may carry `_Size: XS|S|M|L|XL_` (an English-stable marker, like _Verify:_) worth
// XS=1 S=2 M=3 L=5 XL=8 points; an unsized task counts as its feature's median sized task (M when none is sized). When a
// task was ticked is recorded by spec_complete_task (state.ticks[n] = ISO — recordTick); a task ticked before 1.14 falls
// back to its evidence (the first passing run, else the record's time); a tick made by hand has no time and is not counted.
// Velocity = points completed per WORKING day (Mon–Fri, UTC days) over the last FORECAST_WINDOW_DAYS calendar days,
// counted from the day of the first completion in that window through today — project-wide, and per feature once the
// feature has FORECAST_MIN_TASKS completions of its own in the window. A planned feature's ETA = its open points ÷ that
// velocity, in working days from today — or from the working day after the ETA of each unfinished dependency — with a
// ±FORECAST_SPREAD range (low/high chain off the dependencies' low/high). Fewer than FORECAST_MIN_TASKS completions in the
// window: no ETA ("not enough data"). Pure reads of tasks.md + .state.json.
// ---------------------------------------------------------------------------
const SIZE_POINTS = Object.freeze({ XS: 1, S: 2, M: 3, L: 5, XL: 8 });
const RE_SIZE_VALUE = /^\s*`?(XS|S|M|L|XL)`?\s*$/i; // a _Size:_ marker's value (taskMarkerSpans reads the marker)
const FORECAST_WINDOW_DAYS = 28;
const FORECAST_MIN_TASKS = 3;
const FORECAST_SPREAD = 0.25;
const FC_DAY_MS = 24 * 60 * 60 * 1000;
// A task's `_Size:_` (its line or a sub-line, never fenced code) → "XS" | "S" | "M" | "L" | "XL", or null (unsized).
function taskSize(block) {
  for (const line of taskProse(block)) {
    for (const sp of taskMarkerSpans(line)) {
      const m = sp.key === "size" && sp.value.match(RE_SIZE_VALUE);
      if (m) return m[1].toUpperCase();
    }
  }
  return null;
}
// completeTask, right before it ticks a task: when (state.ticks[n] = ISO), written with the call's own state (its evidence
// included). A `ticks` that is not an object (a hand edit) is left as it is — never "repaired" — and nothing is recorded.
// When a DONE task was completed (ms), or null: its tick time, else its own evidence record's first passing run (a
// re-check later on is not the completion), else the record's time.
function taskCompletedAt(state, block, dup) {
  const t = isRecord(state.ticks) ? timeOf(state.ticks[String(block.number)]) : null;
  if (t != null) return t;
  const rec = ownRecord(isRecord(state.evidence) ? state.evidence[String(block.number)] : undefined, block, dup);
  if (!isRecord(rec)) return null;
  const passes = (Array.isArray(rec.history) ? rec.history : []).filter((h) => isRecord(h) && h.command && Number(h.exitCode) === 0)
    .map((h) => timeOf(h.at)).filter((x) => x != null);
  if (passes.length) return Math.min(...passes);
  const at = timeOf(rec.at);
  return at != null ? at : timeOf(rec.noteAt);
}
const fcDay = (t) => Math.floor(t / FC_DAY_MS) * FC_DAY_MS; // the UTC day a time falls on
const fcWeekend = (d) => { const w = new Date(d).getUTCDay(); return w === 0 || w === 6; };
const fcIso = (d) => new Date(d).toISOString().slice(0, 10);
function fcWorkingDays(from, to) { // working days in [from, to], both UTC days
  let n = 0;
  for (let d = from; d <= to; d += FC_DAY_MS) if (!fcWeekend(d)) n++;
  return n;
}
function fcAddWorkingDays(start, n) { // the n-th working day, `start` (when it is one) being the first
  let d = start;
  while (fcWeekend(d)) d += FC_DAY_MS;
  for (let k = 1; k < Math.min(n, 20000); k++) {
    d += FC_DAY_MS;
    while (fcWeekend(d)) d += FC_DAY_MS;
  }
  return d;
}
// Completions [{ t, points }] → the velocity over the window ending `now`. pointsPerDay is given from the first completion
// on; `enough` says whether forecasts may use it (FORECAST_MIN_TASKS completions in the window).
function velocityOf(completions, now) {
  const from = now - FORECAST_WINDOW_DAYS * FC_DAY_MS;
  const win = completions.filter((c) => c.t > from && c.t <= now);
  const points = round2(win.reduce((s, c) => s + c.points, 0));
  const v = { windowDays: FORECAST_WINDOW_DAYS, minTasks: FORECAST_MIN_TASKS, completed: win.length, points, since: null, workingDays: null, pointsPerDay: null, enough: win.length >= FORECAST_MIN_TASKS };
  if (win.length) {
    const first = fcDay(Math.min(...win.map((c) => c.t)));
    v.since = fcIso(first);
    v.workingDays = Math.max(1, fcWorkingDays(first, fcDay(now)));
    v.pointsPerDay = round2(points / v.workingDays);
  }
  return v;
}
// One feature's forecast input: its completions, open points, open / unsized task counts (active tasks only).
function forecastInput(projectDir, name) {
  const dir = path.join(specsRoot(projectDir), name);
  const blocks = taskBlocks(activeTasks(readIfExists(path.join(dir, "tasks.md")) || "", detectTracks(dir)) || "");
  const st = readJson(statePath(dir)).data;
  const state = isObj(st) ? st : {};
  const med = stats(blocks.map(taskSize).filter(Boolean).map((s) => SIZE_POINTS[s])).median;
  const dflt = med != null ? med : SIZE_POINTS.M;
  const pts = (b) => { const s = taskSize(b); return s ? SIZE_POINTS[s] : dflt; };
  const dups = new Set(duplicateTaskNumbers(blocks));
  const completions = [];
  for (const b of blocks) {
    if (!b.done) continue;
    const t = taskCompletedAt(state, b, dups.has(b.number));
    if (t != null) completions.push({ t, points: pts(b) });
  }
  const open = blocks.filter((b) => !b.done);
  return { completions, remaining: round2(open.reduce((s, b) => s + pts(b), 0)), open: open.length, unsized: open.filter((b) => !taskSize(b)).length };
}
// feats: roadmap() features ({ name, phase, percent, unmetDeps }). opts.now (ms / ISO) fixes "today" (tests); opts.cycle:
// roadmap()'s cycle (its features get no ETA). → { velocity, byFeature: { name → forecast } } — forecast: { eta, range:
// [low, high], workingDays, remainingPoints, openTasks, unsizedTasks, pointsPerDay, velocity: "feature" | "project", after? }
// or { eta: null, reason: "done" | "no-tasks" | "not-enough-data" | "dependency" | "cycle", … }.
function forecastData(projectDir, feats, opts = {}) {
  const now = (opts.now != null && timeOf(opts.now)) || Date.now();
  const today = fcDay(now);
  const input = Object.create(null);
  const feat = Object.create(null);
  for (const f of feats) { feat[f.name] = f; input[f.name] = forecastInput(projectDir, f.name); }
  const velocity = velocityOf(Object.values(input).flatMap((x) => x.completions), now);
  const inCycle = new Set(Array.isArray(opts.cycle) ? opts.cycle : []);
  const out = Object.create(null);
  const days = new Map(); // name → { eta, low, high } (UTC day ms) for the dependents' start
  const visiting = new Set();
  const solve = (name) => {
    if (out[name]) return out[name];
    const f = feat[name];
    if (!f) return null; // a dependency that is no feature (a stale roadmap.json entry): never an ETA
    if (visiting.has(name) || inCycle.has(name)) return (out[name] = { eta: null, reason: "cycle" });
    visiting.add(name);
    const res = forecastOne(f);
    visiting.delete(name);
    return (out[name] = res);
  };
  const forecastOne = (f) => {
    if (f.percent === 100) return { eta: null, reason: "done" };
    const x = input[f.name];
    if (!(f.phase === "tasks-ready" || f.phase === "executing") || !x.open) return { eta: null, reason: "no-tasks" };
    const base = { remainingPoints: x.remaining, openTasks: x.open, unsizedTasks: x.unsized };
    const fv = velocityOf(x.completions, now);
    const v = fv.enough ? fv : velocity.enough ? velocity : null;
    if (!v) return { eta: null, reason: "not-enough-data", ...base };
    const unmet = Array.isArray(f.unmetDeps) ? f.unmetDeps : [];
    let start = today, lowStart = today, highStart = today;
    const waiting = [];
    for (const d of unmet) {
      const df = solve(d);
      const dd = df && df.eta ? days.get(d) : null;
      if (!dd) { waiting.push(d); continue; }
      start = Math.max(start, dd.eta + FC_DAY_MS);
      lowStart = Math.max(lowStart, dd.low + FC_DAY_MS);
      highStart = Math.max(highStart, dd.high + FC_DAY_MS);
    }
    if (waiting.length) return { eta: null, reason: "dependency", after: waiting, ...base };
    const need = x.remaining / v.pointsPerDay;
    const at = (from, d) => fcAddWorkingDays(from, Math.max(1, Math.ceil(d - 1e-9)));
    const dd = { eta: at(start, need), low: at(lowStart, need * (1 - FORECAST_SPREAD)), high: at(highStart, need * (1 + FORECAST_SPREAD)) };
    days.set(f.name, dd);
    const res = { eta: fcIso(dd.eta), range: [fcIso(dd.low), fcIso(dd.high)], workingDays: round1(need), ...base, pointsPerDay: v.pointsPerDay, velocity: v === fv ? "feature" : "project" };
    if (unmet.length) res.after = unmet.slice();
    return res;
  };
  for (const f of feats) solve(f.name);
  return { velocity, byFeature: out };
}
// A feature's own velocity (spec_metrics).
function featureVelocity(projectDir, name, opts = {}) {
  return velocityOf(forecastInput(projectDir, name).completions, (opts.now != null && timeOf(opts.now)) || Date.now());
}
// spec_roadmap / ROADMAP.* extras on a roadmap() result: `velocity` (project), each feature's `forecast`, and `overlaps`.
function roadmapExtras(projectDir, rmv, opts = {}) {
  const fc = forecastData(projectDir, rmv.features, { now: opts.now, cycle: rmv.cycle });
  rmv.velocity = fc.velocity;
  for (const f of rmv.features) f.forecast = fc.byFeature[f.name];
  rmv.milestones = milestoneStatuses(projectDir, rmv.features, (opts.now != null && timeOf(opts.now)) || Date.now()); // 1.16 E3
  const msBad = milestoneInvalidInfo(readRoadmap(projectDir)); // 1.16 verify NEW-1: stored entries no status is computed for
  if (msBad) rmv.milestonesInvalid = msBad;
  const ov = featureOverlaps(projectDir, rmv.features);
  rmv.overlaps = ov.pairs;
  if (ov.truncated) rmv.overlapsTruncated = true;
  return rmv;
}
// "2026-10-05 (10-03…10-08)" — the range's year dropped when it is the ETA's; the ETA alone when the range is that one day.
// null without an ETA.
function etaText(fc, lang, cli) {
  if (!fc || !fc.eta) return null;
  const F = i18n.msg(lang).forecast;
  const short = (d) => (d.slice(0, 4) === fc.eta.slice(0, 4) ? d.slice(5) : d);
  const [low, high] = Array.isArray(fc.range) ? fc.range : [fc.eta, fc.eta];
  return (cli ? F.cliEta : F.etaCell)(fc.eta, low === high ? null : short(low), low === high ? null : short(high));
}
// The velocity line (ROADMAP.*, CLI): the rate, or "not enough data" with the count so far.
function velocityText(v, lang) {
  const F = i18n.msg(lang).forecast;
  return v && v.enough ? F.velocity(v) : F.notEnough(v || velocityOf([], Date.now()));
}
// `dev-spec roadmap`'s lines after the features: the velocity once some task was completed in the window (a project that
// has not started prints nothing new), the ETA rule when an ETA is shown, and the cross-feature overlaps.
function roadmapTailLines(r, lang) {
  const F = i18n.msg(lang).forecast;
  const out = [];
  if (r.velocity && r.velocity.completed > 0) out.push(velocityText(r.velocity, lang));
  if ((r.features || []).some((f) => f.forecast && f.forecast.eta)) out.push(F.etaNote(Math.round(FORECAST_SPREAD * 100)));
  if ((r.milestones || []).length) out.push(`🏁 ${i18n.msg(lang).milestone.title}:`, ...r.milestones.map((m) => "  " + milestoneLine(m, lang))); // 1.16 E3
  if (r.milestonesInvalid) out.push("⚠ " + milestoneAttention([], lang, r.milestonesInvalid)[0].msg); // 1.16 verify NEW-1
  const ov = r.overlaps || [];
  if (ov.length) {
    out.push(F.overlap.cliHead(ov.length));
    for (const p of ov) out.push((p.kind === "finished" ? F.overlap.cliFinished : F.overlap.cliActive)(p.a, p.b, overlapFiles(p, lang)));
  }
  return out;
}

// ---------------------------------------------------------------------------
// Cross-feature file overlap (1.14). Two ACTIVE features whose OPEN tasks plan the same files (_Implements:_, compared as
// implementsKey — anchors, ./ and case where the file system folds it dropped; a folder covers every file under it, as in
// next --batch; a glob covers what it matches and its literal folder), or an active feature planning a file a FINISHED
// feature recorded in its drift baseline (state.finished.files): they land on the same files at merge time and one of
// them drifts silently. Not an overlap: two features already ordered by a dependency (either way, transitively — a finished
// one too), or either one declaring `_Supersedes:_` of the other's criteria (a finished one: the active one declaring it). Bounded:
// OVERLAP_MAX_KEYS entries per feature (each at most OVERLAP_MAX_REF_LEN characters), OVERLAP_MAX_GLOB_CHECKS glob comparisons
// whose cost (pattern length × path length) stays under OVERLAP_MAX_GLOB_WORK, OVERLAP_MAX_PAIRS pairs listed.
// Text reads only — nothing is hashed (the SessionStart hook runs it).
// ---------------------------------------------------------------------------
const OVERLAP_MAX_KEYS = 500;
const OVERLAP_MAX_GLOB_CHECKS = 200000;
const OVERLAP_MAX_REF_LEN = 512; // a longer reference is no path anyone plans — skipped (truncated)
const OVERLAP_MAX_GLOB_WORK = 20000000; // DP cells over all glob comparisons (~0.2 s): the SessionStart hook runs this
const OVERLAP_MAX_PAIRS = 50;
const OVERLAP_FILES_SHOWN = 5;
// feats: roadmap() features ({ name, phase, dependsOn }; default: roadmap(projectDir)'s). opts.only: the pairs one feature
// is part of (an active pair either way; a finished pair on its active side). → { pairs: [{ a, b, kind: "active" |
// "finished", files: [rel …], count }], truncated } — a: the active feature (roadmap order first); b: the other one.
function featureOverlaps(projectDir, feats, opts = {}) {
  if (!Array.isArray(feats)) feats = roadmap(projectDir).features;
  const root = specsRoot(projectDir);
  const fold = FOLD_CASE ? (s) => s.toLowerCase() : (s) => s;
  // A project path — not a [placeholder], a "TBD" / "n/a" / "none" / "-" stand-in, the project root or a path leaving it.
  const okKey = (k) => !!k && k !== "." && !/^\[.*\]$/.test(k) && !/^(?:tbd|todo|n\/?a|none|-+|…|\.{3})$/i.test(k) && !k.startsWith("/") && !/^[A-Za-z]:/.test(k) && !k.split("/").includes("..");
  let truncated = false;
  const srcs = [];
  feats.forEach((f, idx) => {
    const dir = path.join(root, f.name);
    const s = { idx, name: f.name, kind: f.phase === "complete" ? "finished" : "active", lit: [], globs: [] };
    const seen = new Set();
    const push = (rel, glob) => {
      const key = fold(rel);
      if (!okKey(key) || seen.has(key)) return;
      if (key.length > OVERLAP_MAX_REF_LEN || seen.size >= OVERLAP_MAX_KEYS) { truncated = true; return; }
      seen.add(key);
      (glob ? s.globs : s.lit).push({ key, rel, glob });
    };
    if (s.kind === "finished") { // complete: only its drift baseline counts (none recorded → nothing to collide with)
      const st = readJson(statePath(dir)).data;
      if (isObj(st) && isObj(st.finished) && isObj(st.finished.files)) for (const rel of Object.keys(st.finished.files)) push(String(rel).replace(/\\/g, "/"), false);
    } else {
      for (const b of taskBlocks(activeTasks(readIfExists(path.join(dir, "tasks.md")) || "", detectTracks(dir)) || "")) {
        if (b.done) continue;
        for (const ref of taskMarkers(b).implements) { const rel = implementsRel(ref); push(rel, isImplementsGlob(rel)); }
      }
    }
    if (s.lit.length || s.globs.length) srcs.push(s);
  });
  const pairs = new Map();
  const hit = (s1, e1, s2, e2) => {
    if (s1 === s2 || (s1.kind === "finished" && s2.kind === "finished")) return;
    let [a, ea, b, eb] = [s1, e1, s2, e2];
    if (a.kind === "finished" || (b.kind === "active" && b.idx < a.idx)) [a, ea, b, eb] = [b, eb, a, ea];
    const k = a.name + "\u0000" + b.name;
    if (!pairs.has(k)) pairs.set(k, { a, b, files: new Map() });
    const shown = eb.glob || (!ea.glob && ea.rel.length >= eb.rel.length) ? ea : eb; // the literal, more specific path
    pairs.get(k).files.set(shown.key, shown.rel);
  };
  // Literal paths: the same key, or one a folder of the other — every key looks itself and its folders up.
  const index = new Map();
  for (const s of srcs) for (const e of s.lit) { if (!index.has(e.key)) index.set(e.key, []); index.get(e.key).push({ s, e }); }
  for (const s of srcs) {
    for (const e of s.lit) {
      const parts = e.key.split("/");
      for (let i = parts.length; i >= 1; i--) for (const o of index.get(parts.slice(0, i).join("/")) || []) hit(s, e, o.s, o.e);
    }
  }
  // Globs (active features only): a literal path it matches or a folder holding its literal part; another glob when either
  // matches the other's pattern.
  for (const s of srcs) {
    for (const g of s.globs) {
      g.match = globMatcher(g.key);
      const parts = g.key.split("/");
      const litParts = [];
      for (let i = 0; i < parts.length - 1 && !/[*?{]/.test(parts[i]); i++) litParts.push(parts[i]);
      g.base = litParts.join("/"); // the glob's literal folders ("src/api" of "src/api/**/*.js")
    }
  }
  let checks = 0, work = 0;
  const spend = (a, b) => { work += (a.length + 1) * (b.length + 1); return ++checks > OVERLAP_MAX_GLOB_CHECKS || work > OVERLAP_MAX_GLOB_WORK; };
  outer: for (const s of srcs) {
    for (const g of s.globs) {
      for (const o of srcs) {
        if (o === s) continue;
        for (const e of o.lit) {
          if (spend(g.key, e.key)) { truncated = true; break outer; }
          if (g.match(e.key) || (g.base && (g.base === e.key || g.base.startsWith(e.key + "/")))) hit(s, g, o, e);
        }
        for (const e of o.globs) {
          if (spend(g.key, e.key) || (work += (e.key.length + 1) * (g.key.length + 1)) > OVERLAP_MAX_GLOB_WORK) { truncated = true; break outer; }
          if (e.key === g.key || g.match(e.key) || e.match(g.key)) hit(s, g, o, e);
        }
      }
    }
  }
  const depsOf = Object.create(null);
  for (const f of feats) depsOf[f.name] = Array.isArray(f.dependsOn) ? f.dependsOn : [];
  const reaches = (from, to) => {
    const seen = new Set();
    const stack = [...(depsOf[from] || [])];
    while (stack.length) {
      const n = stack.pop();
      if (n === to) return true;
      if (seen.has(n)) continue;
      seen.add(n);
      stack.push(...(depsOf[n] || []));
    }
    return false;
  };
  const supCache = new Map();
  const supersedes = (s, other) => { // does s declare _Supersedes:_ of one of other's criteria?
    if (!supCache.has(s.name)) {
      const dir = path.join(root, s.name);
      let set = new Set();
      try { set = new Set(supersedesTrace(projectDir, dir, readIfExists(path.join(dir, "requirements.md")) || "").supersedes.map((v) => v.feature)); } catch { /* unreadable: none */ }
      supCache.set(s.name, set);
    }
    return supCache.get(s.name).has(other.name);
  };
  // A finished pair too: a dependency either way orders them (the active one builds on the finished one — the advice SessionStart
  // and doctor give, "order them with /depend"), or the active one declares _Supersedes:_ of its criteria.
  let list = [...pairs.values()]
    .filter(({ a, b }) => !(reaches(a.name, b.name) || reaches(b.name, a.name) || supersedes(a, b) || (b.kind !== "finished" && supersedes(b, a))))
    .sort((x, y) => x.a.idx - y.a.idx || x.b.idx - y.b.idx)
    .map(({ a, b, files }) => {
      const all = [...files.values()].sort();
      return { a: a.name, b: b.name, kind: b.kind, files: all.slice(0, OVERLAP_FILES_SHOWN), count: all.length };
    });
  if (opts.only) list = list.filter((p) => p.a === opts.only || (p.kind === "active" && p.b === opts.only));
  if (list.length > OVERLAP_MAX_PAIRS) { list = list.slice(0, OVERLAP_MAX_PAIRS); truncated = true; }
  return { pairs: list, truncated };
}
// "src/a.js, src/lib, +3 more" — a pair's files as the messages list them.
function overlapFiles(p, lang) {
  const O = i18n.msg(lang).forecast.overlap;
  return p.files.join(", ") + (p.count > p.files.length ? ", " + O.more(p.count - p.files.length) : "");
}
// ROADMAP.* "needs attention": one line per pair, on its active side (a), naming the other feature.
function overlapAttention(p, lang) {
  const O = i18n.msg(lang).forecast.overlap;
  return (p.kind === "finished" ? O.attentionFinished : O.attentionActive)(p.b, overlapFiles(p, lang));
}
// spec_doctor's cross-feature-overlap detail for `slug` (featureOverlaps {only: slug}).
function overlapDoctorDetail(pairs, slug, lang) {
  const O = i18n.msg(lang).forecast.overlap;
  const act = pairs.filter((p) => p.kind === "active").map((p) => `${p.a === slug ? p.b : p.a} (${overlapFiles(p, lang)})`);
  const fin = pairs.filter((p) => p.kind === "finished").map((p) => `${p.b} (${overlapFiles(p, lang)})`);
  return [act.length ? O.doctorActive(act.join("; "), slug) : null, fin.length ? O.doctorFinished(fin.join("; "), slug) : null].filter(Boolean).join(" · ");
}

module.exports = { progressBar, mid, ROADMAP_I18N, i18nLang, htmlEsc, cleanTaskText, ROW_CACHE, ROW_CACHE_MAX, ROW_CALLS, ROW_OPTS,
  ROW_SCRATCH, rowStatSig, rowProjectSig, roadmapData, roadmapRow, buildAttention,
  roadmapTaskText, roadmapPhaseName, renderRoadmapMd, renderRoadmapHtml, SIZE_POINTS, RE_SIZE_VALUE,
  FORECAST_WINDOW_DAYS, FORECAST_MIN_TASKS, FORECAST_SPREAD, FC_DAY_MS, taskSize, taskCompletedAt, fcDay, fcWeekend,
  fcIso, fcWorkingDays, fcAddWorkingDays, velocityOf, forecastInput, forecastData, featureVelocity, roadmapExtras,
  etaText, velocityText, roadmapTailLines, OVERLAP_MAX_KEYS, OVERLAP_MAX_GLOB_CHECKS, OVERLAP_MAX_REF_LEN,
  OVERLAP_MAX_GLOB_WORK, OVERLAP_MAX_PAIRS, OVERLAP_FILES_SHOWN, featureOverlaps, overlapFiles, overlapAttention,
  overlapDoctorDetail, __link };
