#!/usr/bin/env node
"use strict";

/**
 * dev-spec-driven — the build (1.20). Node core only.
 *
 *   node scripts/build.js            (npm run build) writes the committed mcp/lib/engine/corpus.generated.json — the
 *                                    built-in placeholder corpus, rendered by the engine itself (markdown.js renderCorpusData),
 *                                    stamped with the hash of the sources it was rendered from (CORPUS_SOURCES); every process
 *                                    reads it instead of rendering ~1,165 templates, and renders them as before when the stamp
 *                                    doesn't match
 *                                    — and the committed hooks/stop-claims.generated.json (1.24 r6 I-I4): every language's claim
 *                                    patterns and the prose regexes of the stop gate (guards.js stopClaimFilter), stamped with
 *                                    the sizes of the files they come from (STOP_FILTER_SOURCES) — the Stop hook's pre-filter,
 *                                    read before the engine loads. Neither carries the version (1.26): what they hold is a
 *                                    function of their sources alone, so a release that changes no source leaves both unchanged
 *   node scripts/build.js --check    (npm run check) writes nothing; exit 1 when either committed file differs from a fresh build
 *   node scripts/build.js --bundle [--out <file.js>]   (npm run build:bundle; also `dev-spec bundle`) writes the engine
 *                                    (mcp/lib/engine/) and i18n (mcp/lib/i18n.js, mcp/lib/i18n/) modules as ONE file — by
 *                                    default mcp/lib/spec.bundle.js, git-ignored, NEVER committed — for a slow file system:
 *                                    the facade loads it only with DEV_SPEC_BUNDLE=1 (DEV_SPEC_BUNDLE_PATH: another place) and
 *                                    while it is current (the version, and the size + mtime of every module it holds)
 * The corpus needs a rebuild after changing a file of CORPUS_SOURCES (mcp/lib/i18n.js, mcp/lib/i18n/*, engine/core.js,
 * markdown.js, packs.js, tasks.js, tracks.js) — never for package.json's version alone — the stop-claim filter after changing one of
 * STOP_FILTER_SOURCES (mcp/lib/i18n.js, mcp/lib/i18n/*, engine/guards.js) — mcp/test.js fails until both are committed. Both are
 * deterministic: the same sources give the same bytes (sorted lists, no dates, LF). See docs/maintainers/architecture.md
 * → The build.
 */

const fs = require("fs");
const path = require("path");

const ROOT = path.join(__dirname, "..");
const LIB = path.join(ROOT, "mcp", "lib");
const CORPUS_PATH = path.join(LIB, "engine", "corpus.generated.json");
const BUNDLE_PATH = path.join(LIB, "spec.bundle.js"); // the default place — .gitignore'd
const STOP_CLAIMS_PATH = path.join(ROOT, "hooks", "stop-claims.generated.json"); // 1.24 r6 I-I4 — committed (a clone without hooks/: none)

// The bundled modules of an mcp/lib folder: every .js file of engine/ (folders included) and i18n/, plus the i18n.js facade —
// mcp/lib-relative, "/"-separated, sorted. Not spec.js (the facade chooses between the modules and a bundle) nor
// prompts-resources.js (not the engine: it requires spec.js).
function bundledFiles(lib = LIB) {
  const out = ["i18n.js"];
  const walk = (rel) => {
    for (const e of fs.readdirSync(path.join(lib, ...rel.split("/")), { withFileTypes: true })) {
      const r = rel + "/" + e.name;
      if (e.isDirectory()) walk(r);
      else if (e.name.endsWith(".js")) out.push(r);
    }
  };
  walk("engine");
  walk("i18n");
  return out.sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
}

// The corpus file's text (JSON, one list item per line — a template change is a readable diff). E: the engine of `lib`.
// Stamped with the sources hash only (1.26): the render runs through CORPUS_SOURCES alone (mcp/tests/16-conventions-build.js
// proves the list with V8 coverage — engineVersion's upgrade.js is not in it), so the hash says everything the version could; the
// version stamp only made every release rewrite the file with the same corpus.
function buildCorpus(E, lib = LIB) {
  const data = { generated: "AUTO-GENERATED by scripts/build.js (npm run build) — the built-in placeholder corpus; do not edit",
    sources: E.corpusSourcesHash(lib), ...E.renderCorpusData() };
  return JSON.stringify(data, null, 1) + "\n";
}

// 1.24 r6 I-I4 — the stop-claim filter's text: the Stop hook reads it (hooks/stop-claims.generated.json) to send a message holding no
// claim pattern away before the engine loads. Stamped with each STOP_FILTER_SOURCES file's size as git checks it out (LF, no BOM):
// the hook takes it only while every size matches. No version (1.26): the filter is a function of those files alone, and the
// version never caught what the sizes miss (an edit that keeps every size — that one only a rebuild sees: `npm run check`, the
// suite). E: the engine of `lib`.
function buildStopClaims(E, lib = LIB) {
  const sources = {};
  for (const rel of E.STOP_FILTER_SOURCES) {
    const t = fs.readFileSync(path.join(lib, ...rel.split("/")), "utf8").replace(/\r\n/g, "\n");
    sources["mcp/lib/" + rel] = Buffer.byteLength(t.charCodeAt(0) === 0xfeff ? t.slice(1) : t, "utf8");
  }
  const data = { generated: "AUTO-GENERATED by scripts/build.js (npm run build) — the stop gate's claim patterns, for the Stop hook's pre-filter; do not edit",
    sources, ...E.stopClaimFilter() };
  return JSON.stringify(data, null, 1) + "\n";
}
const hasHooks = () => fs.existsSync(path.dirname(STOP_CLAIMS_PATH));

// The module registry a bundle runs its modules in — emitted verbatim (Function.prototype.toString), so it is real, linted
// code here. DEFS: "rel/path.js" → function (exports, require, module, __filename, __dirname) holding that file's source;
// root: the mcp/lib folder the FACADE passes (its own __dirname) — the modules' original __filename / __dirname are built
// from it, so path-relative code (engineVersion's package.json, the approval guard's CLI path) reads the same files wherever
// the bundle file lives. A relative require resolves inside the registry (Node's semantics: cached before it runs, dropped
// again if it throws), a file the bundle lacks goes to Node's loader, a bare name (Node core) to Node. Each module's
// `module.bundle` is the build stamp (markdown.js reads the embedded corpus through it). → the registry's require (from root).
function moduleRegistry(DEFS, BUNDLE, root, path, nodeRequire) {
  const loaded = new Map();
  const own = (key) => Object.prototype.hasOwnProperty.call(DEFS, key);
  function load(key) {
    const hit = loaded.get(key);
    if (hit) return hit.exports;
    const filename = path.join(root, ...key.split("/"));
    const module = { id: filename, filename, loaded: false, exports: {}, bundle: BUNDLE };
    loaded.set(key, module);
    try {
      DEFS[key].call(module.exports, module.exports, requireFrom(path.posix.dirname(key)), module, filename, path.dirname(filename));
    } catch (e) {
      loaded.delete(key);
      throw e;
    }
    module.loaded = true;
    return module.exports;
  }
  function requireFrom(dir) {
    return function require(id) {
      if (typeof id === "string" && (id.startsWith("./") || id.startsWith("../"))) {
        const key = path.posix.normalize(path.posix.join(dir, id));
        return own(key) ? load(key) : nodeRequire(path.join(root, ...key.split("/")));
      }
      return nodeRequire(id);
    };
  }
  return requireFrom(".");
}

// A bundle's text for the mcp/lib folder `lib` (default: this clone's). Each module is its source verbatim (as Node reads it:
// the bundle is strict, so every module must start "use strict";), stamped with its size and mtime — the facade stats each
// one and takes the bundle only while all still match (an update or an edit since the build: the modules, silently). The
// corpus rides along, rendered by E (the engine of `lib`) from these very sources.
function buildBundle(E, lib = LIB) {
  const files = bundledFiles(lib);
  const stamps = [];
  const defs = files.map((rel) => {
    const abs = path.join(lib, ...rel.split("/"));
    const st = fs.statSync(abs);
    const src = fs.readFileSync(abs, "utf8");
    if (!src.startsWith("\"use strict\";")) throw new Error(rel + ": a bundled module starts with \"use strict\"; (the bundle is strict)");
    stamps.push([rel, st.size, st.mtimeMs]);
    return JSON.stringify(rel) + ": function (exports, require, module, __filename, __dirname) {\n" + src + (src.endsWith("\n") ? "" : "\n") + "},\n";
  });
  // The bundle keeps its version stamp (the facade takes it only while package.json says the same — it is never committed, so it
  // never churns); the corpus it embeds is stamped with its sources hash alone, like the committed one.
  const version = E.engineVersion();
  if (!version) throw new Error("package.json has no x.y.z version: the bundle is stamped with it");
  const corpusText = buildCorpus(E, lib);
  const corpus = JSON.parse(corpusText);
  return [
    "\"use strict\";",
    "// GENERATED by scripts/build.js --bundle (dev-spec bundle) — never edited, never committed. dev-spec-driven " + version + ":",
    "// the engine (mcp/lib/engine/) and i18n (mcp/lib/i18n.js, mcp/lib/i18n/) modules in ONE file, for a slow file system.",
    "// The facade (spec.js) loads it only with DEV_SPEC_BUNDLE=1, while its version is package.json's and every module it",
    "// holds still has the size and mtime stamped below. Each module is its source verbatim, run with its original",
    "// __filename / __dirname; the load order and __link are unchanged. See docs/maintainers/architecture.md → The build.",
    "const CORPUS = " + JSON.stringify(corpusText) + ";",
    "const BUNDLE = Object.freeze({ version: " + JSON.stringify(version) + ", corpusSources: " + JSON.stringify(corpus.sources) +
      ", corpus: () => JSON.parse(CORPUS) });",
    "const FILES = " + JSON.stringify(stamps) + ";",
    "const DEFS = {",
    defs.join(""),
    "};",
    "module.exports = { stamp: { version: BUNDLE.version, files: FILES },",
    "  load: (root) => (" + moduleRegistry.toString() + ")(DEFS, BUNDLE, root, require(\"path\"), require) };",
    "",
  ].join("\n");
}
// Write a bundle → { file, bytes, modules, version }. file: absolute (default mcp/lib/spec.bundle.js); opts.lib: the mcp/lib
// it bundles (default this clone's), opts.E: that folder's engine (default: required from it).
function writeBundle(file = BUNDLE_PATH, opts = {}) {
  const lib = opts.lib || LIB;
  const E = opts.E || require(path.join(lib, "engine", "index.js"));
  const text = buildBundle(E, lib);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, text);
  return { file, bytes: Buffer.byteLength(text), modules: bundledFiles(lib).length, version: E.engineVersion() };
}

// Is the committed corpus what a fresh build writes (CRLF read as LF)? → [relative path] of the stale file(s).
function stale(E) {
  const engine = E || require(path.join(LIB, "engine", "index.js"));
  const out = [];
  const check = (file, text) => {
    let cur = null;
    try { cur = fs.readFileSync(file, "utf8").replace(/\r\n/g, "\n"); } catch { /* missing */ }
    if (cur !== text) out.push(path.relative(ROOT, file).split(path.sep).join("/"));
  };
  check(CORPUS_PATH, buildCorpus(engine));
  if (hasHooks()) check(STOP_CLAIMS_PATH, buildStopClaims(engine));
  return out;
}

function main() {
  const args = process.argv.slice(2);
  const bundle = args[0] === "--bundle" && (args.length === 1 || (args.length === 3 && args[1] === "--out" && /\.js$/i.test(args[2])));
  if (!bundle && !(args.length === 0 || (args.length === 1 && args[0] === "--check"))) {
    process.stderr.write("usage: node scripts/build.js [--check] | --bundle [--out <file.js>]\n");
    process.exitCode = 2;
    return;
  }
  if (bundle) {
    const r = writeBundle(args[2] ? path.resolve(args[2]) : BUNDLE_PATH);
    process.stdout.write("wrote     " + r.file + " (" + r.modules + " modules, " + r.bytes + " bytes) — used with DEV_SPEC_BUNDLE=1" +
      (r.file === BUNDLE_PATH ? "" : " and DEV_SPEC_BUNDLE_PATH=" + r.file) + "\n");
    return;
  }
  if (args[0] === "--check") {
    const s = stale();
    process.stdout.write(s.length ? "stale: " + s.join(", ") + " — run npm run build\n" : "the corpus is up to date (and the stop-claim filter)\n");
    process.exitCode = s.length ? 1 : 0;
    return;
  }
  const E = require(path.join(LIB, "engine", "index.js"));
  const write = (file, text) => {
    let cur = null;
    try { cur = fs.readFileSync(file, "utf8"); } catch { /* new */ }
    const rel = path.relative(ROOT, file).split(path.sep).join("/");
    if (cur === text) return void process.stdout.write("unchanged " + rel + "\n");
    fs.writeFileSync(file, text);
    process.stdout.write("wrote     " + rel + " (" + Buffer.byteLength(text) + " bytes)\n");
  };
  write(CORPUS_PATH, buildCorpus(E));
  if (hasHooks()) write(STOP_CLAIMS_PATH, buildStopClaims(E));
}

if (require.main === module) main();

module.exports = { buildCorpus, buildStopClaims, buildBundle, writeBundle, stale, bundledFiles, CORPUS_PATH, BUNDLE_PATH, STOP_CLAIMS_PATH };
